// Razão social das marcas (fonte: PainelCSGerencial/companies_data.json).
window.RAZAO_MARCAS = (function(){
    var raw = {
        "2 wave": "2wave Ltda",
        "3r lopes": "Rayanne Lopes",
        "a f aires de oliveira ltda": "A F Aires De Oliveira Ltda",
        "a perola collection": "PEROLA COLLECTION INDUSTRIA E COMERCIO LTDA",
        "a rouparia": "ANGELICA APARECIDA DE OLIVEIRA",
        "a&e": "A&e",
        "a.m store": "Andreia Martins",
        "acailandia": "DIAMANTES LINGERIE LTDA",
        "acesso modas": "D. F. L. DA CONCEICAO LTDA",
        "acesso renata porto": "Renata Porto",
        "achadinhos da geni": "Genniffer Dayany Araújo",
        "acqua marine": "S. J. LEE CONFECCOES",
        "actually jeans": "PATRICIA K M LEAL",
        "adama": "Confecções Adama Ltda",
        "aderet modas": "Zenobia Mamani de Laura",
        "adhara": "Alverina",
        "adizza": "Adizza",
        "adizza + distinto": "Adizza + Distinto",
        "adizza distinto": "DISTINTO COMERCIO DE ARTIGOS PARA VESTUARIO LTDA",
        "adriana": "Adriana",
        "adriana cobucci": "Adriana Cobucci ",
        "adryelle": "Adryelle",
        "adsusan": "SUSANA CORI MAMANI 23463640880",
        "aela": "AELA CONFECCOES LTDA",
        "aero summer 1": "Aero Summer",
        "aero summer 2": "Aero Summer",
        "af man & woman": "AF MAN & WOMAN CONFECCOES LTDA",
        "af man & woman interestadual": "Af Man & Woman Confecções Ltda",
        "afetto": "AFETTO MODAS LTDA",
        "afinidades fabrica": "DIAMANTES LINGERIE LTDA",
        "afri.co": "AFRI.CO",
        "ag gestao e n.": "AG GESTAO E NEGOCIOS EIRELI",
        "agarre & use varejo": "Agarre & Use",
        "agarreuse": "AGARRE E USE LTDA",
        "agora use": "Agora Use-kids",
        "agora use kids": "FRANCISCO RIBEIRO ",
        "agridoce": "GALATEIA CONFECCAO LTDA",
        "ain roupas": "CONFECCOES DE ROUPAS AIN LTDA",
        "aingrid plus size": "Patricia Apaza Cutipa",
        "ajo brand": "Jo Modas Confeccao Eireli",
        "alagoinhas": "DIAMANTES LINGERIE LTDA",
        "alam modas": "Rodo Gualberto Cusi Anamuro",
        "alanis": "ALANIS COMERCIO DE ROUPAS EIRELI",
        "alari bolsas e acessorios de couro legitimo": "Alarí bolsas e acessórios",
        "albina": "Albina",
        "alcance jeans": "ALC Industria e Comércio de Roupas Ltda.",
        "alcance jeans ap/ am/ rr/ ma / pa": "MANUELA COSTA FILGUEIRAS",
        "alcance jeans ba": "MANUELA COSTA FILGUEIRAS",
        "alcance jeans es": "MANUELA COSTA FILGUEIRAS LTDA",
        "alcance jeans go/ df/ to": "MANUELA COSTA FILGUEIRAS",
        "alcance jeans mg": "MANUELA COSTA FILGUEIRAS LTDA",
        "alcance jeans ms/ mt": "MANUELA COSTA FILGUEIRAS",
        "alcance jeans pr": "MANUELA COSTA FILGUEIRAS",
        "alcance jeans programado": "MANUELA COSTA FILGUEIRAS",
        "alcance jeans rj": "MANUELA COSTA FILGUEIRAS",
        "alcance jeans rs": "MANUELA COSTA FILGUEIRAS",
        "alcance jeans sc": "MANUELA COSTA FILGUEIRAS",
        "alcance jeans varejo": "MANUELA COSTA FILGUEIRAS",
        "alcance mega polo": "MANUELA COSTA FILGUEIRAS",
        "alda cabral ramos": "Alda Cabral Ramos ",
        "aldo": "ALDO VASCONCELOS DE PAIVA JUNIOR",
        "aldo vasconcelos de paiva junior": "ALDO VASCONCELOS DE PAIVA JUNIOR",
        "alella confeccoes": "ALELLA CONFECCOES",
        "alessandra": "Alessandra",
        "alexandre sartorelli": "Alexandre Sartorelli ",
        "alexsandro de oliveira sampaio": "Alexsandro De Oliveira Sampaio",
        "alforria brasil": "AUGUSTA MENDES FERREIRA",
        "aliados representacoes e assessoria": "Aliados Representações e Assessoria",
        "alice": "MULBORA CONFECÇÕES EIRELI",
        "alice amaral": "ALICE FERREIRA DE SOUZA",
        "aline confeccoes": "CARLOS LABRA",
        "alle_moda": "Alle_Moda",
        "allexia modas": "Y CHUNXIAN",
        "allura brand": "VIGOR TOTAL INDUSTRIA E COM. DO VESTUARIO LTDA EPP",
        "aloicia": "JIN HYUN",
        "alory": "ALORY CONFECCOES EIRELI",
        "alpelo": "Alpelo Confecção e Comercio de Roupas Ltda",
        "alphatryx representacoes": "JULIEMERSON NUNES DE SOUSA 40699921899",
        "alta fe confeccoes": "Alta Fé Confecções",
        "alto atacado katharina brasil  plus size": "QUATRO LETRAS CONFECCOES DE ROUPAS EIRELI",
        "alx modas": "Alexsander Joel Gomez Quispe",
        "ambiente 1": "AMBIENTE 1",
        "ambiente cheina": "Ambiente Cheina",
        "ambiente dados": "Ambiente Dados",
        "amesca confeccoes eireli": "Douglas Harris",
        "amicca": "GAZZY ESMERALDA LTDA",
        "amicia": "LA AMICIA CONFECCAO E COMERCIO EIRELI",
        "amik modas": "JUAN JOSE CHOQUE APAZA",
        "amiska": "CONFECCOES MISS MILLIE INDUSTRIA E COMERCIO DE ROUPAS LTDA",
        "amofany": "Renata",
        "amofany teste dapic": "Amofany Teste Dapic",
        "amondu": "KLESISS CONFECCAO DE ROUPAS LTDA",
        "amore": "AMORE INDUSTRIA E COMERCIO DE ROUPAS LTDA",
        "ana carolina asturiano costa": "Ana Carolina Asturiano Costa",
        "ana cristina alves rodrigues": "Ana Cristina Alves Rodrigues",
        "ana goncalves bom retiro": "RAFAELA LEMARA LTDA",
        "ana goncalves brusque": "CLAUDIA MATOS DA FONSECA EIRELI",
        "ana goncalves estoque": "ANA CAROLINA LEMES",
        "ana goncalves farroupilha": "A/C GONCALVES EIRELI",
        "ana goncalves homologacao bling": "Ana Gonçalves",
        "ana goncalves jacutinga": "LUIZ CARLOS LEMES",
        "ana goncalves tricot prime": "BG LIMITADA",
        "ana moda fashion": "Ana Moda Fashion",
        "ana paula dias": "Ana Paula Dias",
        "anahi": "ALTA MUN BIANCA CONFECCOES LTDA",
        "analiss shine": "Monica Park LTDA",
        "anathia store": "Anathia Confeccoes LTDA",
        "anderson atacado": "FERNANDO FERNANDES INDUSTRIA E COMERCIO DE ROUPAS EIRELI",
        "anderson varejo": "FERNANDO FERNANDES INDUSTRIA E COMERCIO DE ROUPAS EIRELI",
        "andira jeans": "ANDIRA IND E COM DE CONFECCOES LTDA",
        "andre luis nunes tavares": "Andre Luis Nunes Tavares",
        "andrea saba": "DANILO RICARDO DE SANTANA",
        "andreia lucas maruyama": "Andreia Lucas Maruyama",
        "andressa vesti": "Andressa Vesti",
        "andrietta": "ANDRIETTA MODAS E VESTUARIOS LTDA",
        "anemone": "MM21 INDÚSTRIA E COMÉRCIO DE ROUPAS LTDA ",
        "anemone (casemiro)": "ANEMONE INDUSTRIA E COMERCIO DE VESTUARIO LTDA",
        "anemone casemiro": "Anemone",
        "anick": "WKS COMERCIO E CONFECCOES LTDA",
        "anisa": "Confecções Anisa LTDA",
        "ankor - pronta entrega": "Ankor Industria de Vestuário Ltda",
        "ankor design": "Promo Ind e Comercio de Confeccoes LTDA",
        "anna celia": "Anna Celia",
        "anna clara fashion": "Anna Clara Fashion",
        "annamana": "ANNAMANA TEXTIL LTDA",
        "anne blanc": "XY - CONFECCOES LTDA",
        "antonie": "BRUMAE HOLDING LTDA",
        "apoa": "APOA COMERCIO DE ROUPA FEMININA LTDA",
        "apress teen": "MR DE MARTIN LAQUINI LTDA",
        "aqua": "JUST ME INDUSTRIA E COMERCIO DE CONFECCOES LTDA",
        "aqua doce": "CONFECCOES AQUA DOCE LTDA",
        "aquarela modas": "JUVENAL",
        "aracaju 1": "DIAMANTES LINGERIE LTDA",
        "aracaju 2": "DIAMANTES LINGERIE LTDA",
        "aracaju 3": "DIAMANTES LINGERIE LTDA",
        "aramodu": "CONFECÇÕES ARAMODU LTDA",
        "aramodu varejo": "CONFECÇÕES ARAMODU LTDA",
        "arapiraca 1": "DIAMANTES LINGERIE LTDA",
        "arapiraca 2": "DIAMANTES LINGERIE LTDA",
        "araripaca 3": "DIAMANTES LINGERIE LTDA",
        "arary": "Arary comércio de tecidos LTDA",
        "arluh modas": "Ariel Denilson Alarcon Amaru",
        "armored jeans": "Armored Jeans",
        "art bijoux": "Art Bijoux",
        "arte d' vestir | vitoria regia": "Arte D' Vestir | Vitória Regia",
        "arte dvestir": "Arte DVestir",
        "arte dvestir | catarina": "Arte DVestir",
        "artecor": "ART E COR ROUPAS LTDA",
        "artecor bras": "ART E COR ROUPAS LTDA\t",
        "arusha": "ARUSHA COMERCIO DE ROUPAS LTDA.",
        "as marias": "ALEGRA FASHION INDUSTRIA E COMERCIO DE ROUPAS EIRELI",
        "asdn": "ASDN",
        "asha plus": "HYUM JAE LIM",
        "astrya": "Astréia Aparecida Pinheiro",
        "atrendy": "Clarice Soares",
        "attrevida fashion": "Andreia do Amaral Amaral",
        "audio visual": "AV BRAND COMERCIO DE ARTIGOS DO VESTUARIO LTDA",
        "aurami": "Aurami",
        "aurore clothing": "Aurore Clothing",
        "aurum": "GRUPO ASAS CONFECCOES LTDA",
        "auston": "CONFECCOES AUSTON LTDA",
        "ave rara": "RAZAO AVERARA CONFECCOES EIRELI - EPP",
        "avivah": "CONFECÇÕES MIRAGE LTDA - EPP",
        "ayla j modas": "65.972.487 Adasila Arcani Cuaquira",
        "azpex": "CONFECCOES AZPEX LTDA",
        "b. first": "B. FIRST CONFECCOES LTDA",
        "b. rock jeans": "B. ROCK JEANSFASHIONSTORE COMERCIO DE ROUPAS EIRELI",
        "b.b filial": "BLUE BLOSSOM CONFECCOES - EIRELI",
        "b.w multiservices": "Bilal Soueid",
        "bacabal 1": "DIAMANTES LINGERIE LTDA",
        "badocky": "MANTIS TEXTIL IMPORTACAO E COMERCIO DE ARTIGOS DE VESTUARIO LTDA",
        "balboa modas": "BALBOA MODAS LTDA",
        "balum baby": "Bruna Stramosk",
        "bangali": "Bangali Modas e Acessórios Ltda",
        "banoffe brand": "Danila Pedro Rodrigues Serviços e Negócios",
        "barraca do willinha": "Barraca do Willinha",
        "bauarte": "BOLSAS BAUARTE ACESSORIOS DA MODA LTDA",
        "bc3 modas": "Betza Cuentas Gonzales",
        "be eight": "BE EIGHT INDUSTRIA E COMERCIO DE ROUPAS LTDA",
        "be eight - homol totvs": "BE EIGHT - Homol Totvs",
        "beach cat atacado": "Beach Cat Atacado",
        "beatriz coltro": "Rafael Fernandes Barison",
        "becky": "BECKY CONFECCOES LTDA",
        "befree denim": "FORUS INDUSTRIA E COMERCIO DE ROUPAS - EIREL",
        "begkids": "Begkids",
        "beige store": " L S X COMERCIO DE CONFECCOES LTDA",
        "beija-flor roupas": "Carla Simone Vieira Da Silva",
        "bejams modas": "Sintia Choquemamani Anamuro",
        "bekymiro": "Rebeca Amalia Ramos Mamani",
        "bela e chic": "Bela E Chic",
        "bela gaia": "Bela Gaia Comercio de Bolsas e Acessorios LTDA",
        "bela palu": "PAULA VIEIRA",
        "belamor": "BELAMOR MODAS LTDA",
        "belart": "WS MODAS LTDA",
        "belem 1": "DIAMANTES LINGERIE LTDA",
        "belem 2": "DIAMANTES LINGERIE LTDA",
        "believe moda evangelica": "Gilliard Custódio Neves e cia Ltda",
        "bella donna": "Bella Donna",
        "bella donna varejo": "BELLA DONNA MODA BRAS ARTIGOS DO VESTUARIO LTDA",
        "bella fe ​": "RODRIGO ASSIS DA MATA​",
        "bella hit": "Bella Hit Confeccoes",
        "bella jolie": "Bella Jolie",
        "bella moda intima": "Bella Moda Intima LTDA",
        "belle epoque": "LA VIE FASHION COMERCIO DE ROUPAS EIRELI",
        "belm brands": "BELMONTH STREETWEAR",
        "belmonth clothing": "belmonth clothing",
        "bem-me-quer": "E. T. LEE CONFECCOES",
        "benesh": "HUT CONFECCOES - EIRELI",
        "benevenuto": "REGINEIDE BENEVINUTO SOUSA DE ABREU",
        "berenice merhey": "Berenice Merhey",
        "bestie": "CONFECÇÕES BESTIE LTDA",
        "betania": "Betania",
        "betelgeuse": "Betelgeuse",
        "betsey": "BETSEY CONFECCOES LTDA",
        "beula": "CONFECCOES BIGANSON-TEX LTDA",
        "bilcon modas": "Bilcon Comercio de Roupas LTDA",
        "bina midsize": "Patrícia Brizola ",
        "biotipo jeans": "CONFECCOES ALTA MODA LTDA",
        "biro": "BRW MODAS LTDA",
        "black jeans": "ARJES CONFECCOES LTDA",
        "blackberry": "Fabricia Carvalho",
        "bling bling": "Bling Bling ",
        "bloony brand": "Bloony brand LTDA",
        "blossom": "KEUM WON KIM CONFECCOES",
        "blubetty bom retiro": "KAPITON CONFECÇÕES LTDA",
        "blubetty brusque": "KAPITON CONFECÇÕES LTDA",
        "blubetty cianorte": "KAPITON CONFECÇÕES LTDA",
        "blubetty desativada": "KAPITON CONFECÇÕES LTDA",
        "blubetty maringa": "KAPITON CONFECÇÕES LTDA\t",
        "blubetty mega polo": "KAPITON CONFECÇÕES LTDA",
        "blubetty rio preto": "KAPITON CONFECÇÕES LTDA",
        "blubetty varejo": "KAPITON CONFECÇÕES LTDA",
        "blue beni": "Blue Beni",
        "blue blossom": "BLUE BLOSSOM CONFECCOES - EIRELI",
        "bm bolsas": "GFP ACESSÓRIOS DA MODA LTDA",
        "bm jeans": "Carla Rosângela Barboza",
        "boemia chic": "GISELE OLIVEIRA PINA",
        "boise": "BOISE CONFECCOES LTDA",
        "bokeh": "CONFECCOES CHESED LTDA",
        "boladinhos kids": "FERNANDA C RODRIGUES",
        "bold for life": "Magnun dos Santos Pereira",
        "bolovo productions": "BOLOVO PRODUCTIONS LTDA",
        "borisu": "MODAS BORISU NATTE LTDA",
        "boutique bella flor": "Nathalya Barbosa Silva",
        "boutique denise santos": "BOUTIQUE COMERCIO DE ROUPAS E ACESSORIOS LTDA",
        "braba": "BRABA.BRAND CRIACOES LTDA",
        "braga camisaria": "Braga Camisaria",
        "braga pedido": "Braga Camisaria",
        "braga pronta entrega": "Braga Camisaria",
        "bragas imports": " Camila da Silva Braga",
        "branca": "Branca",
        "brascol atacado": "Brascol",
        "brascol loja": "ONESHOP DISTRIBUIDORA LTDA",
        "brascol online": "Brascol",
        "brasilia": "DIAMANTES LINGERIE LTDA",
        "brilho trend": "Giovanna Carvalho ",
        "brithamel modas": "Brithamel Modas Comercio do Vestuario LTDA",
        "bruna modas": "Bruna Modas",
        "bruno mendes": "Bruno Mendes",
        "bruno representante": "Bruno",
        "brytch jeans": "INDUSTRIA DE CONFECCAO KDM EIRELI",
        "brytch jeans loja fisica": "INDUSTRIA DE CONFECCAO KDM EIRELI",
        "buccanes": "JURRO INDUSTRIA E COMERCIO DE CONFECCOES LTDA",
        "buddha spa uniformes e insumos": "BUDDHA SPA BELENZINHO",
        "buh": "Desativo",
        "by mi tomazela": "Prana Store Confecções LTDA",
        "by picle": "By Picle",
        "by.marcelo medeiros": "MARCELO PINTO P DE MENESES",
        "byanca marcelino de souza": "Byanca Marcelino De Souza",
        "cahelon": "Cahelon",
        "caio santos": "Caio Santos",
        "cajubrasil - pronta entrega": "Top Confecções de Votuporanga LTDA ",
        "cajubrasil - venda programada": "Top Confecções de Votuporanga LTDA ",
        "califor": "CALIFOR CONFECÇÕES LTDA",
        "califor filial": "Califor",
        "camboriu": "CAMBORIU LTDA",
        "cambos jeans": "Cambos Jeans",
        "camerata": "Confecções Camerata Ltda",
        "camila style": "Silbio Mullisaca",
        "camisaria real.com": "JR DANTAS ESTILO DETERMINADO LTDA",
        "camiseta fabrica": "TEASER ALL STYLE COMERCIO DE ROUPAS E ACESSORIOS LTDA",
        "campina grande": "DIAMANTES LINGERIE LTDA",
        "campos pijamas": "IRAILDES SOUZA CAMPOS NUNES",
        "canoni": "CANONI CONFECCOES LTDA",
        "canoni varejo": "CANONI CONFECCOES LTDA",
        "carla oliveira brand": "FAHANNA | CARLA FARIA CONCEPT ",
        "carlos da silva": "Carlos Da Silva",
        "carlos henrique": "Carlos Henrique Pereira",
        "carmem soares": "Carmem Soares",
        "carmen": "Carmen",
        "carmen jeans": "Carmen Jeans",
        "carmila": "CONFECCOES IRMAS BRISOLLA LTDA",
        "caroll collection": "CAROLL CONFECCOES IMPORTACAO E EXPORTACAO LTDA",
        "caronly": "CARONLY LTDA",
        "carpiem": "DC COMERCIO DE SEMIJOIAS EIRELI",
        "caruaru": "DIAMANTES LINGERIE LTDA",
        "cashier": "CASHIER CONFECCOES LTDA ",
        "cassia queiroz silva": "Cassia Queiroz Silva",
        "castanhal": "DIAMANTES LINGERIE LTDA",
        "casualli": "C.R. LABEGALINI",
        "cattleya moda": "CATTLEYA",
        "cauipe moda praia": "Cauípe Moda Praia",
        "cavweillers": "CavWeillers",
        "ce moda feminina": "FABIO GUERRA DOS SANTOS",
        "celavie": "ACACIA BRANCA CONF LTDA",
        "celavie filial": "Acacia Branca Conf ltda",
        "celeb": "Jung Min Seo",
        "celer": "B.J. INDUSTRIA E COMERCIO DE CONFECCOES LTDA",
        "celinha caputo": "Celinha Caputo",
        "chance jeans": "CHANCE JEANS INDUSTRIA E COMERCIO LTDA",
        "charisma": "Charisma",
        "charisma - matriz": "CHARISMA .",
        "charity": "CONFECCOES CHARITY EIRELI",
        "charmonte": "Jns modas ltda",
        "chaville fashion": "CHAVILLE FASHION LTDA",
        "cheers/lyah": "MODAS VISION LTDA - EPP",
        "chess": "Chess Industria E Comercio Ltda",
        "chocolate doce": "AHM CONFECCOES EIRELI",
        "chocolate doce loja 1": "Chocolate Doce Loja 1",
        "chocolate doce varejo": "CHOCOLATE DOCE VAREJO",
        "chocomel": "FL MARINHO LITZ CONFECÇÕES",
        "chocomel filial": "FNJ MODAS LTDA​",
        "chocris": "CONFECCOES CHOCRIS LTDA",
        "chocris aimores": "JOO YOUNG KIM CONFECCOES LTDA",
        "chocris jp": "CONFECCOES CHOCRIS LTDA",
        "chocris mega": "DIJ KIM CONFECCOES",
        "cibele": "Cibele",
        "cibele rb feitoza": "Cibele Rb Feitoza",
        "cicero": "Cicero",
        "cintia.ca modas": "Humberto Chura Huanca",
        "citta": "SAERA CONFECÇÕES LTDA ",
        "clajan": "Clajan industria e comércio de malhas e crochêt ltda",
        "claribel confeccoes": "Marcelino Flores Mamani",
        "classicstyle@integracao1.com": "classicstyle@integracao1.com",
        "cleide soares": "Cleide Soares",
        "clichy": "CAN FLOW CONFECCOES LTDA",
        "cliente vip - boladinhos kids": "Boladinhos Kids",
        "cliente@manse.com": "cliente@manse.com",
        "clio": "CLIO CONFECCOES IMPORTACAO E EXPORTACAO LTDA",
        "clomee": "Clomee Confeccoes LTDA",
        "closet 35": "RDL INDUSTRIA E COMERCIO DE CALCADOS ROUPAS E ACESSORIOS LTDA",
        "closet da de": "Andressa Guimarães",
        "closet moura": "AYANNE CAROLINE ALVES DE MOURA",
        "closet open": "DELUXE ATELIER COMERCIO DE CONFECCOES LTDA",
        "clovis calcados": "COMPRA CERTA COMERCIAL LTDA",
        "clube lucky jeans": "L.L MARTINS",
        "clube zaya": "Clube Zaya",
        "clubinho da magica": "Clubinho da Magica Comercio de Artigos Infantis LTDA ",
        "clubsoda": "OSHER CONFECCOES LTDA",
        "clubsoda bom retiro": "CASTELO DA MODA COMERCIO DO VESTUARIO LTDA",
        "cocacy": "Cocacy",
        "cocci": "COCCI MODAS EIRELI",
        "cocoa": "CONFECCOES COCOA EIRELI",
        "codi codi": "MOONKA CONFECCOES LTDA - EPP",
        "codigo zero": "MALHARIA CATARINENSE INDUSTRIA E COMERCIO DE ARTIGOS DO VESTUARIO LTDA.",
        "cof cof": "MODAS COF COF LTDA",
        "coinage": "COINAGE CONFECCOES LTDA - EPP",
        "colecao inverno 2026": "Nicoboco Pedido",
        "colly atacado": "CAMILA PEREIRA DA SILVA ROUPAS",
        "compton": "TREND CORP COMERCIO IMPORTACAO E EXPORTACAO LTDA",
        "conceito mika": "CONCEITO MIKA LTDA",
        "confec. mauricio atacado": "CONFECCOES MAURICIO LTDA",
        "confec. mauricio varejo": "CONFECCOES MAURICIO LTDA",
        "confeccoes abel modas": "34353873000108",
        "confeccoes tendenza": "CONFECCOES TENDENZA LTDA",
        "confession": "LUZES DA MODA COMERCIO DE ROUPAS LTDA - ME",
        "consciencia jeans": "NOVA SANTA FE CONFECCOES DE ROUPAS LTDA ",
        "contagie": "CONTAGIE INDUSTRIA E COMERCIO DE CONFECCOES LTDA",
        "cony green": "CONFECCOES E MODAS CONY GREEN LTDA",
        "copine": "CONFECCOES COPINE LTDA",
        "coqueta bom retiro": "CONFECCOES COQUETA LTDA",
        "coqueta bras": "Azul Royal Comércio e Confecções de Roupas Ltda",
        "cr comercio": "CR COMERCIO E CONFECCAO DE ACESSORIOS DA MODA LTDA",
        "creme canela": "Kalliane Parizi",
        "criativa da crianca": "Criativa Da Crianca",
        "cris fashion": "CRIS FASHION MODAS LTDA",
        "crisfael": "C F COMERCIO IMPORTACAO EXPORTACAO DE ACESSORIOS DA MODA LTDA",
        "cristian modas": "Cristian Modas LTDA",
        "cristiane barbosa": "CRISTIANE BARBOSA DE OLIVEIRA",
        "cristina crizan": "Cristina Crizan ",
        "cristovao": "Cristovao",
        "crocker jeans": "US BRASIL IND E COM DE ROUPAS LTDA",
        "crocker jeans alto atacado": " US BRASIL INDUSTRIA E COMERCIO DE ROUPAS LTDA",
        "cubo cubo": "CONFECÇÕES CUBO CUBO LTDA",
        "cvl moda - cd nova friburgo": "SOULTEX TECIDOS LTDA",
        "cvl moda - cidade da moda": "SOULTEX TECIDOS LTDA",
        "cvl moda - feirao das malhas": "SOULTEX TECIDOS LTDA",
        "cvl moda - moda rio": "SOULTEX TECIDOS LTDA",
        "cvl moda - plaza polo": "SOULTEX TECIDOS LTDA",
        "cvl moda - ponte da saudade": "SOULTEX TECIDOS LTDA",
        "cvl moda - varejo": "SOULTEX TECIDOS LTDA",
        "d mais representacoes": "D MAIS REPRESENTACOES",
        "d' veras moda": "AGUIAR E SOUSA LTDA",
        "d'liny lingerie": "A&C DE OLIVEIRA LTDA",
        "d'lions": "D LIONS INDUSTRIA LTDA",
        "dadri": "Dadric Jeans",
        "dadric jeans": "Dadric Jeans",
        "daiany confeccoes": "TITO WILY QUISPE COLQUE - COMERCIO E CONFECCAO",
        "daline": "Maria Gleuca Rodrigues Ferenandes",
        "dallew jeans": "Dallew Jeans LTDA",
        "danque": "Newcreate Confecções Eirelli",
        "danque.": "Yesul Confecções - EIRELI",
        "dazz modas": "Dazz Modas",
        "deeper": "DEEPER CONFECCOES LTDA",
        "delas plus size": "EUSTAQUIO E ODILIA COMERCIO DE ROUPAS LTDA",
        "deleite": "CONFECCOES DE ROUPAS THEJU LTDA",
        "delia modas fashion": "Délia Modas Bras",
        "delia modas varejo": "DELIA MODAS FASHION LTDA.",
        "delight": "DELIGHT MODA FEMININA LTDA",
        "deluxe atelier": "DELUXE ATELIER COMERCIO DE CONFECCOES LTDA",
        "demissy": "TREND COLLECTION CONFECCOES LTDA",
        "denise": "Denise",
        "denovo": "DE NOVO CONFECCOES LTDA",
        "desativo": "desativo",
        "deslum...": "DESLUMBRADA CONFECCOES LTDA",
        "detha store": "Thalita Tameirao Deveza Matos",
        "dgb modas": "DIRCE GABRIELLY BOROCHOK",
        "di luise": "DI LUISE CONFECCOES LTDA",
        "di trajan": "Di Trajan",
        "diamantes centro frecheirinha": "DIAMANTES LINGERIE LTDA",
        "diamantes desativada": "DIAMANTES LINGERIE LTDA",
        "diamantes l - varejo": "DIAMANTES LINGERIE LTDA",
        "diamantes leads": "DIAMANTES LINGERIE LTDA",
        "diamantes lingerie": "DIAMANTES LINGERIE LTDA",
        "diamantes lingerie bl": "DIAMANTES LINGERIE LTDA",
        "diamantes lingerie pedreiras": "DIAMANTES LINGERIE LTDA",
        "diamantes lingerie_": "DIAMANTES LINGERIE LTDA",
        "diamantes maraba": "DIAMANTES LINGERIE LTDA",
        "diamantes matriz": "DIAMANTES LINGERIE",
        "diamantes mossoro": "DIAMANTES LINGERIE LTDA",
        "diamantes pinheiro": "DIAMANTES LINGERIE LTDA",
        "diamantes representantes": "DIAMANTES LINGERIE LTDA",
        "dicollani denim brusque": "KAPITON CONFECCOES LTDA",
        "dicollani denim cianorte": "KAPITON CONFECCOES LTDA",
        "dicollani denim lombroso": "KAPITON CONFECCOES LTDA",
        "dicollani denim maringa": "KAPITON CONFECCOES LTDA",
        "dicollani denim mega polo": "KAPITON CONFECCOES LTDA",
        "dicollani denim ribeiro de lima": "KAPITON CONFECCOES LTDA",
        "dicollani denim rio preto": "KAPITON CONFECCOES LTDA",
        "dicollani denim.": "KAPITON CONFECÇÕES LTDA",
        "dicollani varejo": "KAPITON CONFECÇÕES LTDA",
        "diego fagundes": "Diego Fagundes",
        "diferenca denim": "Trend Modas",
        "differenza": "Georgia Da Silva Junquilho",
        "dilomon": "KANGDE COMERCIO DE CONFECCAO LTDA",
        "distinto": "Distinto",
        "diva": "Diva",
        "divadonna": "UNDERFASHION MODA INTIMA LTDA",
        "divadonna intimates": "LAURA MARQUES NUNES INTIMATES LTDA",
        "divadonna underfashion": "LAURA MARQUES NUNES INTIMATES LTDA",
        "divas vero": "Veronica Pinto Cancari",
        "divina mulher": "DIVINA MULHER COMERCIO DE ROUPAS LTDA",
        "divina peca": "LOUISE MUNIZ PEREIRA",
        "djiele moda bebe": "DJIELE CONFECCOES LTDA",
        "dmrx": "Djalma Rodriguez ",
        "doce danca": "C. C CHASSOT",
        "doce flor": "JYP CONFECCOES LTDA",
        "doce infancia kids teen": "Vanessa Silva Alves",
        "docevida": "ELAINE MATOS IACOMOLSKI CONFECCOES E COMERCIO LTDA​",
        "dolce vita": "JONG WOOK KIM",
        "doll store": "Doll House",
        "dolps": "Luw Confecções Ltda",
        "dolps - feira": "LUW CONFECCOES LTDA",
        "dominio conceito": "Dominio Conceito",
        "dona charme": "Dona Charme Confecções Eireli​",
        "dona charme cianorte": "D CHA CONFECCOES LTDA",
        "dona charme hd": "DCH CONFECCOES LTDA",
        "dona charme maringa": "D CHA CONFECCOES LTDA",
        "dona ro": "CAMPARIM COM. E VAREJISTA DE VEST E ACESSORIOS EIRELI",
        "donna da lua": "DONNA DA LUA INDUSTRIA E COMERCIO LTDA",
        "donna da lua loja": "DONNA DA LUA INDUSTRIA E COMERCIO LTDA",
        "donna ritz": "Donna Ritz",
        "donna rizza": "D & S Modas Roupas em Geral Ltda",
        "donna stella": "Rayssa Ohana Salton Chagas",
        "donna veste": "Marcia Garcia Da Silva Ribeiro",
        "dots": "JJY Choi conf me",
        "douglas harris": "E.LABORATORIO DE CRIACAO LTDA",
        "drama": "CONFECCOES DRAMA LTDA",
        "dreams atacado": "Paulo Roberto Fonte da Silva",
        "dress us": "DUOSIS COMERCIO LTDA - ME ",
        "dress2shine": "Samantha Massafeli",
        "drika confeccoes": "Drika Confeccoes Antonio Adriano da Silva Confeccoes",
        "drika confeccoes 2": "Drika Confeccoes Antonio Adriano da Silva Confeccoes",
        "duas brand": "R. E. INDUSTRIA E COMERCIO LTDA",
        "dulce color": "DULCE COLOR CONFECCOES LTDA",
        "dunamis": "CONFECCOES DUNAMIS LTDA",
        "duni teen": "Duniteen Modas",
        "duo representacao": "DUO REPRESENTACAO E GESTAO",
        "e s t i m e": "CONFECÇÕES ESTIME LTDA",
        "e s t i m e  varejo": "CONFECÇÕES ARTE E MISS LTDA",
        "eagle rock": "MOONBRIDGE COMERCIAL LTDA",
        "ecko": "Ecko pedidos",
        "ecletica z": "JCR CONFECCOES IMPORTACAO E EXPORTACAO LTDA",
        "ecletica z filial": "JCR CONFECCOES IMPORTACAO E EXPORTACAO LTDA",
        "eddia modas": "65.739.077 LIDIA CALLE DE CALLE",
        "eder jose sangregorio": "Eder Jose Sangregorio",
        "edge clothing": "Jaqueline N S T comércio Ltda",
        "edi saraiva & under varejo": "Nova Geração Saraiva Com. Imp. e Exp. LTDA",
        "edi saraiva gravataria": "Nova Geracão Saraiva Com. Imp. e Exp. LTDA",
        "edjalma": "Edjalma  Oliveira Rodrigues Alcantara",
        "edval ramalho santanna": "Edval Ramalho Santanna",
        "efri modas": "RENE MAMANI PARADA",
        "ego jeans": "RLS ARTIGOS DE VARIEDADES EIRELLI",
        "egoiste": "RLS ARTIGOS DE VARIEDADES EIRELLI",
        "egoiste collection mega polo": "LAVINIA COMERCIO E INDUSTRIA DE BOLSAS E ROUPAS LTDA",
        "egoiste plus": "Egosite Plus",
        "ejd calizaya estilos": "Jhonatan Calizaya Pairo",
        "eklacia": "Confeccoes J Cosi Ltda",
        "elae": "Confeccoes Geração Elae LTDA",
        "elaveste plus size": "SANG CHUL LEE CONFECCOES",
        "elice": "CESAR AUGUSTO DE OLIVEIRA TORRES",
        "elisha": "RICARDO JO CONFECCOES",
        "ellen": "Ellen ",
        "ellen one": "CONFECCOES ELLEN ONE LTDA - EPP",
        "elvis luchezi": "Elvis Luchezi ",
        "elvis representacoes": "Elvis Representacoes",
        "emdu": "Cristina",
        "emili": "JO YOUN CONFECCOES LTDA",
        "emillly": "Emillly",
        "emporio duarte": "Talitha Duarte Ribeiro",
        "emporio modas": "Gustavo",
        "empresa 2": "EMPRESA 2",
        "encantto estilo": "Encanto Estilo",
        "enchantee femme": "Andrezza Senesi Cortonesi",
        "enfasy": "JHONATAN ROSA BATISTA",
        "entretons": "ENTRETONS CONFECCOES LTDA",
        "entretons - representantes": "ENTRETONS CONFECCOES LTDA",
        "equilibree": "Equilibree confeccoes LTDA",
        "equivoco": "L ORSA MODAS E CONFECCOES LTD",
        "equivoco mega polo": "Lorsa Modas e Confecções LTDA",
        "era uma vez": "ROUPAS DE BEBE E ENXOVAIS LTDA",
        "erica modas123": "54.810.903 Concepcion Miranda Vitoria",
        "erica rios de oliveira": "Erica Rios De Oliveira",
        "erika de de morais nunes": "Erika De De Morais Nunes",
        "erilluz jeans": "Erilluz Jeans",
        "erp confeccoes mauricio": "ERP Confeccoes Mauricio",
        "esnouba": "Maviael Junior ",
        "espaco de moda": "Espaço de Moda SP Confecções Ltda",
        "espaco hada": "Espaço Hada",
        "esperanca": "ESPERANCA MODAS LTDA",
        "essence fashion": "ESSENCE FASHION COMERCIO DE ROUPAS E ACESSORIOS LTDA",
        "esstica e puxa": "D CRISS CONFECCOES EIRELI",
        "estacao fit": "ESTACAO FIT CONFECCOES DE MODA FEMININA LTDA",
        "estilo coy": "COY COMERCIO DE CONFECCAO EIRELI",
        "estilo da torcida": "Luiz Fernando De Oliveira",
        "estilo fashion plus": "ESTILO FASHION PLUS COMERCIO DE ARTIGOS DO VESTUARIO E ACESSORIOS LTDA",
        "estime by artemiss filial": "CONFECCOES ARTE E MISS LTDA",
        "estratosfera": "E. INDUSTRIA E COMERCIO DE CONFECCAO LTDA",
        "etonnant": "ETONNANT CONFECCOES DE ROUPAS EIRELI  ",
        "etta": "ETTA COMERCIO E CONFCÇÕES DE ROUPAS LTDA",
        "eunice": "CONFECCOES EUNICE LTDA",
        "eunice silva santos": "Eunice Silva Santos",
        "evelyn fashion": "Evelyn Fashion",
        "evian": "MGA MODAS LTDA",
        "excluir": "EXCLUIR",
        "exinia": "EXINIA CONFECCOES E COMERCIO LTDA",
        "exprim": "ACLOE INDUSTRIA E COMERCIO DE ROUPAS LTDA",
        "ezee": "EZEE CONFECCOES DE ROUPAS EIRELI",
        "fabiano": "Fabiano",
        "fabiano araujo": "Fabiano Araujo",
        "fagian": "Method Trade Importação e Exportação LTDA​",
        "fajos": "MARIA DE FATIMA R M SOUZA EPP",
        "fama fashion": "FAMA FASHION CREACOES LTDA",
        "fammix": "FAMMIX CONFECCOES DE ROUPAS EIRELI",
        "fanyland": "FANYLAND",
        "fascinius": "Neila Alves de Magalhães LTDA",
        "fashion girl atacado": "Fashion Girl Oliver Goncalves Confeccoes LTDA",
        "fashion noire": "DV SHINE CONFECCAO E COMERCIO DE ROUPAS LTDA",
        "fashionista": "BE PRETTY CONFECCOES LTDA",
        "fatima": "Fatima",
        "favorita modas": "Maria Tereza Neves De Lima",
        "favorita plus jeans": "FAVORITA JEANS PLUS LTDA",
        "fb exclusive co. / the sailor denim": "FB EXCLUSIVE CO. LTDA",
        "feira de santana 1": "DIAMANTES LINGERIE LTDA",
        "felps confeccoes": " FELIPE MOLINA GARCIA DA SILVA 03200440171",
        "ferlu modas feminina": " VIRGILIO LAYME ARUQUIPA",
        "fernanda cardoso rodrigues monteiro": "Fernanda Cardoso Rodrigues Monteiro",
        "fernando antonio matias": "Fernando Antonio Matias",
        "fernando rosa": "Fernando Rosa",
        "ferraz lima representacoes": "FERRAZ LIMA REPRESENTACOES COMERCIAIS LTDA",
        "fesperamor": "C. S. Choi Modas",
        "fialho store modas": " Cleirce Salvador Fialho",
        "fiest jeans": "Wibe Confecções Eireli",
        "filial": "FILIAL",
        "filial teste alexia": "FILIAL TESTE ALEXIA",
        "fina e chic": "Fina e Chic",
        "fire": "VICTOR LAGE LEITE FREIRE LTDA",
        "first jeans modinha": "Kenia Carla Barbosa ",
        "fit clothing line": "VINICIUS DALCIN",
        "fitae": "Fitae - Indústria e Comércio de Roupas Ltda",
        "flavia borges cruvinel": "Flavia Borges Cruvinel",
        "flo maria": "G. O PEREIRA INDUSTRIA E COMERCIO DE ROUPAS LTDA",
        "flor de lis": "Daniela de Azevedo Lima",
        "flor do mato": "Flor do Mato ",
        "florenc life": "FLORENCE CONFECCOES LTDA",
        "florita": "Florita Atacado de Confecções Ltda",
        "flowfa": "DTJX INTELIGÊNCIA EM NEGÓCIOS LTDA",
        "folle moda feminina": "FOLLE COMERCIO DE CONFECCOES LTDA",
        "fortaleza 1": "DIAMANTES LINGERIE LTDA",
        "fortaleza 2": "DIAMANTES LINGERIE LTDA",
        "fortaleza 3": "DIAMANTES LINGERIE LTDA",
        "fortaleza 5": "DIAMANTES LINGERIE LTDA",
        "four one jeans": "F.O. Modas Ltda",
        "four one jeans varejo": "F.O. Modas Ltda",
        "fpm blue": "DASTUM COMERCIO DE ROUPAS LTDA - ME",
        "francisco filho dantas da trindade": "FRANCISCO FILHO DANTAS DA TRINDADE CONFECCOES",
        "french": "GUARNIERIUS MODA LTDA",
        "full stop": "VIROU MODA CONFECCOES LTDA",
        "fyhe": "Quebela Fashion Confecções",
        "g&b bros": "G B Bros I Bruno Nunes da Silva - Vestuarios​",
        "gab": "CONFECCOES DE ROUPAS ESPATHI EIRELI",
        "gabifit": "GABIFIT CONFECCOES - EIRELI",
        "gabifit varejo": "GABIFIT CONFECCOES - EIRELI",
        "gabriela/ maria lucia": "Gabriela/ Maria Lucia",
        "gaby makes": "Marca de Teste",
        "gaby modas atacado": "55421588000149",
        "gabyanna confeccoes": "GABYANNA CONFECCOES LTDA",
        "garage": "ADAGIO STORE LTDA",
        "garage varejo": "MILKY WAY CONFECCOES LTDA",
        "garanhuns": "DIAMANTES LINGERIE",
        "garcia": "Garcia",
        "gaven": "Gaven Roupas e Acessórios",
        "gazie modas": "Constantina Aguilar Vela",
        "genesis jeans": "GENESIS JEANS LTDA",
        "genesis jeans varejo": "GENESIS DENIM LTDA",
        "gestor top -  my sistema - restore modas": "Gestor Top -  MY SISTEMA - Restore Modas",
        "gigantinho kids": "Marta Vitória Andrade da Silva",
        "gilkai modas": "G J DE SOUZA ARTIGOS DE VESTUARIO",
        "gio feminine": "Irineu Junior dos Santos",
        "girls store": "NAYARA CRISTINA TEODORO DE SOUZA",
        "gisele zuppo": "GISELE ZUPPO ACESSORIOS EIRELI",
        "gissary modas": "David Maximo Arcani Lopez Confeccoes",
        "gitaa": "GITAA COMERCIO CONFECCOES EIRELI",
        "gitaa varejo": "GITAA COMERCIO CONFECCOES",
        "glam": "GLAM FASHION CONFECCOES E COMERCIO LTDA - EPP",
        "glam varejo": "CHEERS CONFECCOES E COMERCIO LTDA ",
        "glaucineide ferreira maia brando": "Glaucineide Ferreira Maia Brando",
        "gliss jeans (pr)": "JONIDES PARO COMERCIO DE CONFECCOES",
        "gliss jeans (sjrp)": "JURRO INDUSTRIA E COMERCIO DE CONFECCOES LTDA",
        "gliss jeans (sp)": "JURRO INDUSTRIA E COMERCIO DE CONFECCOES LTDA",
        "globe": "CONFECCOES GLOBE LTDA",
        "gnose representacao": "GNOSE REPRESENTACAO LTDA",
        "go padel": " Rogério Pires Costa ME",
        "gois connection": "LEILDO BATISTA DE GOIS",
        "gold belle": "GOLD BELLE INDUSTRIA E COMERCIO DE ROUPAS LTDA",
        "gowara": "Conf. Gowara Ltda EPP",
        "gowara espirito santo": "CONFECCOES GOWARA LTDA",
        "grapete": "CONFECCOES DE ROUPAS GRAPETE LTDA",
        "grasielly lopes santana abreu": "Grasielly Lopes Santana Abreu",
        "green aviamentos": "GREEN CINTOS E AVIAMENTOS LTDA",
        "gringa elisa": "MODA GRINGA INTERNACIONAL LTDA",
        "gringa elisa - desativado": "Fernanda Costa",
        "gringa total bras": "MODA GRINGA INTERNACIONAL LTDA",
        "gringa vautier": " MODA GRINGA INTERNACIONAL LTDA",
        "grit move": "Grit Move Monteiro Monteiro LTDA",
        "groovy forever": "GROOVY FOREVER CONFECÇÕES LTDA - EPP",
        "groovy night": "GROOVY NIGHT CONFECCOES SOCIEDADE UNIPESSOAL LTDA",
        "gross hunter": "Gross Hunter LTDA",
        "grupo l2m": "MCG COMERCIO DE ARTIGOS DO VESTUARIO LTDA",
        "grupo oka + dachshund": "OKA INDUSTRIA DO VESTUARIO EIRELI",
        "grupo paraiso": "CELMA DE ASSIS ROSSATO & CIA LTDA",
        "gts  plus": "GTS PLUS conf.ltda",
        "guarabira": "DIAMANTES LINGERIE LTDA",
        "gule": "Erre Erre Confecções Ltda",
        "gutiban": "CONFECCOES FLOR DA NOITE EIRELI",
        "h skin": "H SKIN CONFECCOES",
        "hanabee": "ESLEE CONFECCOES LTDA",
        "handara boa viagem": "HANDARA BOA VIAGEM",
        "handara boa vista": "HANDARA BOA VISTA",
        "handara carlos gomes": "HANDARA CARLOS GOMES",
        "handara distribuicao": "LLV INDUSTRIA E COMERCIO DE CONFECCOES LTDA",
        "handara empresarial": "HANDARA EMPRESARIAL",
        "handara fabrica": "HANDARA FABRICA",
        "handara feira de santana": "HANDARA FEIRA DE SANTANA",
        "handara garanhuns": "HANDARA GARANHUNS",
        "handara maraponga": "HANDARA MARAPONGA",
        "handara metro": "HANDARA METRO",
        "handara olinda": "HANDARA OLINDA",
        "handara reduto": "HANDARA REDUTO",
        "handara representantes": "HANDARA",
        "handle jeans": "F H DA SILVA TECIDOS E CIA LTDA",
        "hanna look": "HANNA LOOK CONFECCOES EIRELI",
        "happy boy": "D. A. DE SOUSA",
        "happy cat": " BARBARA PEREIRA GONCALVES ​",
        "hard adventure": "HARD ADVENTURE INDUSTRIA E COMERCIO DE ROUPAS E EQUIPAMENTOS LTDA",
        "harmonia fashion": "HLK MODAS E CONFECCOES EIRELI",
        "hellen carolina": "HELLEN CAROLINA MASSUDA CASTRO",
        "hellen moda feminina": "KELLY HIDALGO SALAZAR",
        "heloh": "INDUSTRIA DE VESTUARIO JOAQUIM OLIVEIRA E FILHO LTDA",
        "hemix": "HEMIX CONFECCOES LTDA",
        "hidrogenio": "HIDROGENIO INDUSTRIA E COMERCIO DE ROUPAS LTDA",
        "hirus": "CONFECCOES BONDADE LTDA",
        "hismael": "Hismael",
        "holinzzstone": "HOLINZZSTONE",
        "holliday store": "Karla Maraisa da Silva Confecções ME",
        "hot pink": "Nathalia Ju Hyun Jin",
        "i lov's fashion": "SUK CHAN HWANG COMERCIO DE BIJOUTERIAS",
        "i love bikini": "I Love Bikini beachwear com eireli",
        "i o l z z e bras": "Iolzze Confecções Ltda",
        "i1 modas": "I1 MODAS EIRELI",
        "iconica moda feminina": "Icônica Moda Feminina",
        "idrissi dress": "IDRISSI CONFECCOES EIRELI",
        "igmar": "Diana Patricia Marcani Ulo​",
        "ignite collection": "IGNITE COLLECTION",
        "igor sousa": "Igor Sousa",
        "imagine jeans": "Comercial Textil Denim 1 Ltda",
        "imagivan": "Imagivan Industria e Comercio de Malhas Ltda.",
        "imperatriz": "DIAMANTES LINGERIE LTDA",
        "impere": "IMPERE CONFECCOES EIRELI",
        "imporio fitness": "Imporio Fitness",
        "in love - matriz": "IN LOVE CLOTHING EIRELI",
        "in love catarina": "IN LOVE CLOTHING EIRELI",
        "in love clothing": "IN LOVE CLOTHING EIRELLI",
        "ina": "CONFECCOES S. TELLES LTDA",
        "inativo alto atacado katharina brasil  plus size": "QUATRO LETRAS CONFECCOES DE ROUPAS EIRELI",
        "incentive": "CONFECCOES INCENTIVE LTDA",
        "infini - jundiai": "Wabi-Sabi Modas Eireli - EPP",
        "infini - outlet": "INDUSTRIA E COMERCIO DE ROUPAS INFINI EIRELI",
        "infini - vila mariana": "Blive Modas Ltda - EPP",
        "infini - vila olimpia": "Diamoni Modas Eireli EPP",
        "infini aimores": "INDUSTRIA E COMERCIO DE ROUPAS INFINI EIRELI",
        "infini jundiai": "WABI-SABI MODAS LTDA",
        "infini mega": "Indústria e Comércio de Roupas Infini Eireli ",
        "infini miller": "INDUSTRIA E COMERCIO DE ROUPAS INFINI EIRELI",
        "infini vila mariana": "Blive Modas Ltda - EPP",
        "infini vila olimpia": "DIAMONI MODAS EIRELI",
        "innocence": "SUN JOO KIM CONFECCOES",
        "inquieta": "CONFECCOES DE ROUPAS INQUIETA LTDA",
        "instar": "CLASSY MISSY CONFECCAO DE ROUPAS LTDA",
        "integracao@wooc.com": "integracao@wooc.com",
        "inverno": "CONFECCOES DE ROUPAS GLOBAL CO. LTDA.",
        "iolzze": "IOLZZE CO CONFECCOES LTDA",
        "iona": "MICHELLE BARBOSA DIAS",
        "iralda carneiro portela": "Iralda Carneiro Portela",
        "irene caetano": "Irene Caetano",
        "isa & co": "Kerolen Aparecida Rosa",
        "issa modas": "E. ROSA MOLLO HUANCA - ME",
        "issexy": "MAX GIRLS CONFECCOES E COMERCIO LTDA",
        "issexy treinamento": "Issexy Treinamento ",
        "it look": "CONFECCOES MILLA LTDA",
        "itabaiana": "DIAMANTES LINGERIE LTDA",
        "ivaneide lima ferreira da silva": "Ivaneide Lima Ferreira Da Silva",
        "izuz jeans americana": "RAVERGE INDUSTRIA E COMERCIO DE CONFECCOES LTDA",
        "izuz jeans mirassol desativado": "SUSI CARLA COLOMBI E LORENZONI",
        "izza": "Izza",
        "izzat jeans": "ZITROS INDUSTRIA E COMERCIO DE CONFECCOES LTDA",
        "j&d elegance": "Jennyfer Rabelo dos Santos",
        "j&r modas feminina": "J&R Modas Feminina LTDA",
        "jackie o modas": "RMR COMERCIO DE VESTUARIOS LTDA",
        "jacobs modas": "Jacobs Modas",
        "janacloset moda festa": "Janacloset Store",
        "janacloset store": "Janaina Olicino",
        "janaina aguiar vilete": "Janaina Aguiar Vilete",
        "janainy pereira pinto": "Janainy Pereira Pinto",
        "jay jones": "John Jones Jeans Confeccoes LTDA",
        "jay k": "CONFECCOES GOWARA LTDA",
        "jazz plus": "Jazz Plus",
        "jdl filial": "JDL MODAS",
        "jdl loja 2": "JDL MODAS",
        "jdl modas": " JOHNNY TOLA MAMANI",
        "jdl modas rio": "JDL Modas ",
        "jeanseria bom retiro": "KAPITON CONFECÇÕES LTDA",
        "jeanseria ribeiro de lima": "KAPITON CONFECÇÕES LTDA",
        "jeanseria varejo": "KAPITON CONFECÇÕES LTDA",
        "jefferson ludugerio": "Jefferson Ludugerio",
        "jessia santos da silva": "Jessia Santos Da Silva",
        "jessica": "Jessica",
        "jga o manto": "Jefferson Moraes",
        "jhoana modas": "Jhon Abel Huaraka Ccahuana",
        "jilem modas": "Jilem Modas",
        "jj fashion": "CONFECCOES E MODAS CONY GREEN LTDA",
        "jl modas": "Liz Lorrayne Alves Magalhaes",
        "jn fraldas": "JN FRALDAS",
        "joao pessoa": "DIAMANTES LINGERIE LTDA",
        "joao pessoa 2": "DIAMANTES LINGERIE LTDA",
        "joao pessoa 3": "DIAMANTES LINGERIE LTDA",
        "joao pessoa 4": "DIAMANTES LINGERIE LTDA",
        "joao werneck": "Joao Werneck",
        "joatan coitinho": "Joatan Coitinho",
        "joelik": "JOELIK INDUSTRIA E COMERCIO DE CONFECCOES LTDA",
        "john cunningham": "MORAES & FEITOSA LTDA",
        "join casemiro": "DLJ CONFECCOES LTDA",
        "join curves joaquina": "DLJ CONFECCOES LTDA",
        "join miller": "JULIA A. H. INDUSTRIA E COMERCIO DE ROUPAS LTDA",
        "jorge rosa": "Jorge Rosa ",
        "jose benedito pratt": "Jose Benedito Pratt ",
        "jose carlos belas": "Jose Carlos Belas",
        "jose luiz domingos": "Jose Luiz Domingos",
        "josh menswear": "JORGE GOMES RIBEIRO CONFECÇÕES",
        "josiane dinallo": "Josiane Dinallo",
        "jp monteiro": "BAUARTE MODA LTDA",
        "ju modas": "A J H HWANG MODAS",
        "jubora": "CONFECCOES JUBORA EIRELI",
        "jule semijoias": "JULE COMERCIO E ACESSORIOS LTDA",
        "julia andrade bijuterias": "Julia Andrade Bijuterias",
        "julia plus": "JULIA 618 INDUSTRIA E COMERCIO DE ROUPAS LTDA",
        "julia plus rio": "VR CHOQUECALLATA",
        "july modas": "ARMINDA JULIA MOLLO GAU",
        "junior sapienza": "Junior Sapienza",
        "jurandir": "Jurandir",
        "just denim": "Just Denim Confecções Ltda",
        "k- official jeans": "AFFINICAO INDUSTRIA E COMERCIO DE CONFECCOES LTDA",
        "kaessi": "K. S. LEE CRIACOES LTDA.",
        "kafka baby": "KAFKA BABY INDUSTRIA E COMERCIO DE CONFECCOES LTDA",
        "kafka baby varejo": "Kafka Baby",
        "kalamarka store": "Kalamarka.store LTDA",
        "kalli": "CONFECCOES KALLI EIRELI",
        "kanolly": "MODAS KANOLLY EIRELI",
        "kansas lindgri": "KANSAS LINDGRI REPRESENTACOES",
        "karal": "OLIVEIRA PATRICIO - ARTIGOS DO VESTUARIO LTDA",
        "karmani": "AMARIN CONFECCOES LTDA",
        "katharyne wilmond p p martins": " Katharyne Wilmond P P Martins",
        "katia": "Katia",
        "katia andrade": "Katia Andrade",
        "kativeiro jeans": "KATIVEIRO JEANS WEAR LTDA​",
        "kauly": "KAULY COM ROUPAS LTDA",
        "kauly site": "Kauly ",
        "kayla plus size": "CONFECCOES E COMERCIO MANGOSTAR EIRELI",
        "kelly rodrigues joao teodoro": "Kelly Rodrigues",
        "kelly rodrigues shop caninde": "Kelly Rodrigues",
        "kelly rodrigues store​": "KELLY RODRIGUES STORE LTDA",
        "kesses": "KESSES CONFECCOES LTDA",
        "kids club": "Kids Club",
        "kings sneakers": "Kings Sneakers Comercio Eletrônico Eireli EPP",
        "kinway moda praia": "KINWAY CONFECCOES MODA PRAIA LTDA",
        "klassee boutique": "KLASSEE BOUTIQUE LTDA",
        "klic kids": "Klic Kids Confeccoes LTDA",
        "kokada": "MK MODAS LTDA",
        "kroft": "Kroft Confecções Ltda",
        "kslook": "K. S. Lee Criacoes Ltda",
        "kvg oficial": "KVG Oficial",
        "l&d representacoes": "L&D REPRESENTACOES",
        "l2m kids": "MCG COMERCIO DE ARTIGOS DO VESTUARIO LTDA",
        "la bella": "ISA BELLA MODAS LTDA",
        "la chocole": "MODAS E ARTEFATOS CHOCOLEITE LTDA",
        "la chocole showroom": "La Chocolê Showrom",
        "la lima": "CONFECCOES GOIABELA LTDA",
        "la mora": "La Mora Confecções Ltda",
        "la tay denim": "LA TAY COMERCIO DE ARTIGOS DO VESTUARIO E SERVICOS EIRELI",
        "lady bella": "A. Kenia Da Silva ",
        "laleskaa": "Laleskaa",
        "laras moda fitness": "LARAS MODA LTDA",
        "larosy lingerie": "LAROSY LINGERIE INDUSTRIA E COMERCIO DE CONFECCOES LTDA",
        "lasala": "CONFECCOES LASALA LTDA",
        "laura de falco": "Laura De Falco",
        "lavida": "MODAS LAVIDA ­ EIRELI ­ ME",
        "layza aguiar": "Jeferson Nunes Gonçalves Ramos LTDA",
        "lc multimarcas": "Leonardo Costa",
        "le brand": "Letícia Batista Guimarães",
        "le ricard bom retiro": "Modas Linne Comercio de Roupas Ltda",
        "le ricard lf": " LF CONFECCOES LTDA",
        "le ricard online": "NATANAEL AHN CONFECCOES LTDA",
        "leandra": "Leandra",
        "leda putencio": "Leda Putencio",
        "legacy": "Maria Alessandra do Nascimento Nogueira",
        "leluz shoes": "Andreza Silva",
        "lemier mega polo": "KAZ INDUSTRIA E COMERCIO DE ROUPAS LTDA",
        "lemier miller": "KAZ INDUSTRIA E COMERCIO DE ROUPAS LTDA",
        "lemier xavantes": "Lemier Kaz Industria e Comercio de Roupas LTDA​",
        "lemise": "LM ROUPAS E ACESSORIOS EIRELI",
        "lenner plus size": "Veridiana R N M Castanho confeccoes",
        "lesly modas": "​Lesly Shiomara Febrero Calle",
        "lesto": "LESTO CONFECÇÕES LTDA",
        "leva store": "LEVA COMERCIO DE ARTIGOS DO VESTUARIO E ACESSORIOS LTDA",
        "levitheo": "A L INDUSTRIA DE CONFECCOES LTDA",
        "lexes fashion": "LEXES CONFECCOES LTDA",
        "lf acessorios em geral": "LEO FRANCO CONDO TUNQUE",
        "libero style": "Liberô style Ltda",
        "licommo": "Confecções Licommo LTDA",
        "lidia fontgaland store": "Maria Lenita Oliveira Pimenta ",
        "lie": "Wildes Gomes Correia",
        "life activewear": "Matheus José da Silva",
        "lilabetta": "LILABETTA CONFECCOES LTDA",
        "lilaliz - ceara": "P C DE ARAUJO INDUSTRIA E COMERCIO LTDA",
        "lilaliz - centro fashion": "P C DE ARAUJO INDUSTRIA E COMERCIO LTDA",
        "lilaliz - digital": "P C DE ARAUJO INDUSTRIA E COMERCIO LTDA",
        "lilaliz - juazeiro": "P C DE ARAUJO INDUSTRIA E COMERCIO LTDA",
        "lilaliz - loja metro": "P C DE ARAUJO INDUSTRIA E COMERCIO LTDA",
        "lilaliz - maraponga": "P C DE ARAUJO INDUSTRIA E COMERCIO LTDA",
        "lilaliz - offstore": "P C DE ARAUJO INDUSTRIA E COMERCIO LTDA",
        "lilaliz - online": "P C DE ARAUJO INDUSTRIA E COMERCIO LTDA",
        "lilian plus": "CONFECCOES LILIAN LTDA",
        "lily daisy": "Atelier Lily Daisy Ltda.",
        "lima representacao": "Lima Representacao",
        "lima ritz": "Lima Ritz Confeccao LTDA",
        "limone modas": "LIMONE STORE LTDA",
        "lina jesus de brito": "Lina Jesus De Brito",
        "linha cruzada atacado": "LINHA CRUZADA CONFECCAO LTDA",
        "linha cruzada jeans varejo": "Linha cruzada Jeans ",
        "linny by sanee": "SANEE FASHION MODAS LTDA - EPP",
        "lipcem": "CONFECCOES LIPCEM LTDA",
        "liria cristina fiorillo": "Liria Cristina Fiorillo",
        "liriumix": "MIX ROUPAS E ACESSORIOS LTDA",
        "little star": "LITTLE STAR CONFECCOES LTDA",
        "liv style casa": "LIV STYLE LTDA ",
        "liv style go": "LIV STYLE LTDA ",
        "liv style sp": "LIV STYLE LTDA ",
        "liz bijux e acessorios": "Liz Bijux e Acessorios LTDA",
        "lizbella meninas": "LIZ BELLA E MINI MAN ROUPAS INFANTIS LTDA",
        "lm dream shop": "LM DREAM SHOP LTDA",
        "loderro": "CONFECCOES LODERRO LTDA",
        "loja 2": "Loja 2",
        "loja diamantes lingerie": "DIAMANTES LINGERIE LTDA",
        "loja dois": "Jp Comércio De Roupas",
        "loja giah": "Giah Comercio de Roupas e Acessorios LTDA",
        "loja kings": "KINGS SNEAKERS FRANQUIAS LTDA",
        "loja mini diva": "Aldemira Da Silva",
        "lolly polly": " Lolly Polly Confeccoes LTDA",
        "longhini semijoias": "Cintia Longhini",
        "look hill": "LOOK HILL CONFECCOES LTDA EPP",
        "look kids": "ANA PAULA DIAS ",
        "lorsa": "LORSA MODAS E CONFECCOES LTD",
        "lorsa - bom retiro": "L ORSA MODAS E CONFECCOES LTDA",
        "lov club": "Lov Club",
        "lov. it.": "WELOVIT CONFECCOES LTDA",
        "lsj confeccoes": "66.023.849 CASIMIRO SANCHEZ PINTO",
        "ltz veronez": "Rafael veronez ugliano",
        "lucia": "Lucia ",
        "luciana pais moda evangelica": "SANCHES & PAIS COM ROUPAS II LTDA",
        "luciana pais site": "Luciana Pais Site",
        "luciana viana do vale": "Luciana Viana Do Vale",
        "lucibella": "LUCIVANIA L DA SILVA E CIA LTDA",
        "luciene de oliveira do nascimento": "Luciene De Oliveira Do Nascimento",
        "lucimar ferreira": "Lucimar Ferreira ",
        "lucinha dio moda": "Ana Lucia De Queiroz Pontes Sousa",
        "lucky company": "L.L MARTINS",
        "luis carlos lopes": "Luis Carlos Lopes",
        "luiz roque fanin": "Luiz Roque Fanin",
        "lumiere": "LUMIERE MODA FESTA LTDA",
        "lumina": "BASIC JESUS COMERCIO DE VESTUARIO LTDA",
        "lumini jeans": "Lumini Jeans Industria e Comercio de Artigos do Vestuario LTDA",
        "lunny curves": "SHANES MODAS LTDA",
        "lupim camisaria": "LUPIM INDUSTRIA E COMERCIO DO VESTUARIO LTDA",
        "lupus wear": "LUPUS CONFECCOES LTDA",
        "lutkem & co": "Leandro Lutke",
        "lv moda festa": "Valeria Silva",
        "m muller representaes": "M Muller Representaes",
        "ma che bella confeccoes": "MA CHE BELLA CONFECCOES E COMERCIO DE ROUPAS LTDA",
        "maceio 1": "DIAMANTES LINGERIE LTDA",
        "maceio 2": "DIAMANTES LINGERIE LTDA",
        "maceio 3": "DIAMANTES LINGERIE LTDA",
        "maclagen": "M E A ART LTDA",
        "mafiusu": "MP RUGERO COMERCIO E CONFECCAO",
        "magda fitness": "Sivoneide A da silva confecções",
        "magda moda intima": "Social Sivoneide A da silva Confecções",
        "magnolia lingerie": "COMERCIO E INDUSTRIA DE ROUPAS BRANCAS MAGNOLIA LTDA",
        "mais moda atacado": "Lucas Lautert Ltda",
        "mais um fashion": "Mais Um Fashion ",
        "maite miyao": "MAITE MIYAO ARTIGOS DO VESTUARIO LTDA",
        "maite miyao bling homologacao": "Maite Miyao bling homologacao",
        "malagueta": "CONFECCOES MALAGUETA EIRELI",
        "malhas di bom gosto": "Malhas Di Bom Gosto",
        "malu sena  kadu representaes": "Malu Sena  Kadu Representaes ",
        "malvada plus": "Malvada Favorita ",
        "mamani": "CONFECCOES MAMANI & MAMANI LTDA​",
        "manaca": "VISUH CONFECCOES LTDA ­ EPP",
        "manga rosa pink": "CONFECCOES MANGA ROSA EIRELI",
        "manoel": "Manoel",
        "manoel florencio junior": "Manoel Florêncio Junior ",
        "manse": "produção ",
        "manse@integracao.com": "manse@integracao.com",
        "mar em festa": "MF Praia Industria e Comercio de Confecções LTDA",
        "mar quente": "Mar Quente",
        "marbella atacadista": "MARBELLA COMERCIO ATACADISTA DE CONFECCOES LTDA",
        "marbelle lingerie": "CASTRO E KINNER COMÉRCIO DE VESTUÁRIO LTDA",
        "marcelo medeiros": "MARCELO PINTO P DE MEDEIROS",
        "marcio cardoso": "Marcio Cardoso",
        "marcos mohamede": "Marcos Mohamede",
        "mardone igor normando almeida": "Mardone Igor Normando Almeida",
        "mare beachclub": "NOUET COMERCIO DE CONFECÇÕES E BIJOUTERIAS LTDA.",
        "maria assessoria": "Maria Assessoria",
        "maria bella": "A L R ARAGAO",
        "maria chica": " JPL Roma Modas e Acessórios",
        "maria chica varejo": " JPL Roma Modas e Acessórios",
        "maria de chita": "MARIA DE CHITA CONFECCOES LTDA",
        "maria de lourdes de vitro torres oliveira": "Maria De Lourdes De Vitro Torres Oliveira",
        "maria diva": "Maria Diva",
        "maria dos prazeres feitosa": "Maria Dos Prazeres Feitosa",
        "maria dutra jeans": "Maria Dutra Indústria De Confecções LTDA",
        "maria dutra jeans - varejo": "Maria Dutra Indústria De Confecções LTDA",
        "maria fuxico": "M F COMERCIO DE ROUPAS E ACESSORIOS EM GERAL LTDA",
        "maria lima": "R D ARNAUD SHOJI",
        "maria lima toritama": "RD CONFECCOES DE ROUPA EIRELLI",
        "maria lima varejo": "RD CONFECCOES DE ROUPAS LTDA",
        "maria lindinalva da silva": "Maria Lindinalva Da Silva",
        "maria luiza soares de matos": "Maria Luiza Soares de Matos",
        "mariicota sttore": "BRENO FELIPE",
        "marilene": "Marilene",
        "marilia": "Marilia",
        "maris representaes": "Maris Representaes",
        "marli": "Marli ",
        "martt": "LELIS FASHION CONFECCOES E COMERCIO LTDA",
        "martt varejo": "Martt",
        "mary acessorios": " Mary Acessorios LTDA",
        "master brusque": "RECCO, RECCO E CIA LTDA",
        "master ranking": "MASTER RANKING",
        "mattos wear": "Claudia Santos de Matos",
        "mavem": "FLAVIA MAGALLI S BRANDAO LTDA",
        "mavenza collection": "57.354.897 Miguel Angel Davalos Bernal",
        "mavi store": "Mavione Militao De Souza",
        "mavolle": "PAULA YOLANDA LUIZ CAPOVILLA CONFECÇÕES",
        "mavolle representantes": "Mavolle Representantes",
        "max acessorios bras": "D QUILLE VELASQUE",
        "maxima modas": "D W L Juchani Modas",
        "mazarin": "CONFECCOES MAZARIN LTDA - EPP",
        "mazinho": "Mazinho",
        "meiatres": "Meiatres Comércio de Vestuário Ltda.",
        "meire helen closet": "Meire Helen Custodio Guimaraes",
        "melanina": "MELANINA IND E COM DE ROUPAS LTDA",
        "melanina outlet": "MELANINA IND E COM DE ROUPAS LTDA",
        "melifer": "MELIFER CONF LTDA",
        "melis": "CONFECCOES MELIS LTDA",
        "melove": "ANDRE YOONHO KO",
        "mendry": "CONFECCAO DOUBLE K P RICK IMP E EXP LTDA",
        "menina bonita": "MEB INDUSTRIA E COMERCIO DE CONFECCOES LTDA",
        "menina gata | kr1 jeans": "MENINA GATA E KR1 JEANS INDUSTRIA E COMERCIO DE CONFECCOES LTDA",
        "merci modas": "CONFECCOES DE ROUPAS GIODANO LTDA",
        "mfitgyn": "MFITGYN LTDA",
        "mi&co": "Mi&co confecsao",
        "mia larissa modas": "Mia Larissa Modas LTDA",
        "michelis modas": "Bertha Samo Samo",
        "michelle": "Michelle",
        "michelle modas filocolkema": "F C Mamani",
        "miiss collection": "Miiss Collection",
        "miit": "Sinsedae Modas Eireli ",
        "mika": "MIKA LTDA",
        "milalai": "Confecções MLL Ltda",
        "milenka modas": "Regoberto Quenta Quispe",
        "miliore": "Confeccoes Miliore LTDA",
        "millennium assessoria de moda": "Millennium Assessoria de Moda",
        "milvest": "CREACOES MILVEST EIRELI",
        "mindi": "DO & DU CONFECCOES LTDA",
        "mini lady - mini lord": "Mini Lady ind e com ltda",
        "minick": "Miria Antunes",
        "minolli": "M J R DO NASCIMENTO LTDA",
        "mireya": "Mireya",
        "mis pedrosa": "ERIKA MISLAINNY PEDROSA LAMENHA",
        "misael": "Misael",
        "misalta": "MISHAMNA & MISALTA COMERCIO E ASSESSORIOS DE ROUPAS LTDA",
        "mishamna brasil": "MISHAMNA & MISALTA COMERCIO E ASSESSORIOS DE ROUPAS LTDA",
        "mishin fishin": "FISHIN CONFECCOES LTDA",
        "misluke": "Thais Jyodid Calderon Chumacero",
        "miss alfa": "MISS ALFA COMERCIO DE ROUPAS LTDA",
        "miss misses": "Dack Com Ltda",
        "missmanu": "M. A. DE SOUZA PEREIRA",
        "missmel": "GILMA MARIA SIMAO LTDA",
        "mixxon": "MIXXON MODAS EIRELI",
        "miyu modas": "M. Fernandez Candia - Miyu Modas",
        "mj fashion": "MALI JACOB",
        "mk representacao": "MK REPRESENTACAO COMERCIAL",
        "mm&m assessoria": "Mario Nunes",
        "moca chic": "MOCA CHIC COMERCIO DE ROUPAS E ACESSORIOS LTDA",
        "mocinha charmosa": "Francisco Wagner Oliveira da Silva",
        "moda galvez": "Hugo Quispe Layme",
        "moda inn": "CONFECÇÕES SIMON LTDA",
        "modas carla": "MODAS CARLA PLUS SIZE LTDA",
        "modas clarice": "Anita Capiona Yanari",
        "modas condor": "DENILSON CONDORI MOLLO CONFECCOES",
        "modas faviola": "Faviola Mamani Callizaya",
        "modas fiore": "Mamonde Modas LTDA",
        "modas gio": "MODAS GIO LTDA ­ ME",
        "modas gmf": "MODAS G.M.F COMERCIO DE VESTUARIO LTDA",
        "modas golis": "Martha Aruquipa Castano",
        "modas itsen": "Modas Itsen LTDA",
        "modas keyla": "HOLWIN ADEMAR BARRETO GUTIERREZ",
        "modas mishely": "SANDRA MARDONIA JAIMES ORELLANA",
        "modas namine": "NAMINE CONFECCOES LTDA",
        "modas nj": " Nicanor Choque Choque",
        "modas shemyl & hanna": "Ramiro Perez Giron",
        "modinhas reymar": "MARIA EUGENIA APAZA QUISPE",
        "moeda justa": "Moeda Justa ",
        "moeda justa servicos": "MOEDA JUSTA SERVIÇOS (attasoft)",
        "moirai": "Moirai Conf. de Roupa Eireli",
        "mokkai jeans": "Mokkai Jeans ltda",
        "mon clos": "CAN FLOW CONFECCOES LTDA",
        "monette": "S.H.HAN CONFECÇÕES DE ROUPAS",
        "monnika marikinha": "Monnika Marikinha",
        "monnika marikinha varejo": "Monnika Marikinha",
        "morena charme": "MORENA CHARME INDÚSTRIA COMÉRCIO LTDA",
        "morena charme varejo": "MORENA CHARME INDÚSTRIA COMÉRCIO LTDA",
        "morina": "Morina",
        "mosaique": "CONFECCOES BOLUX LTDA",
        "mottive": "PROBELLAS CONFECCOES LTDA - EPP",
        "moustache multimarcas": "BUCK COMERCIO VAREJISTA DE VESTUARIO E ACESSORIOS LTDA",
        "mrcia helena theodoro fernandes": "Márcia Helena Theodoro Fernandes",
        "multimarca pecas": "Joaquina Ferreira Do Santos",
        "muna": "MIXXON MODAS LTDA",
        "munnah": "INDUSTRIA DE CONFECCOES MUNNAH LTDA.",
        "murano": "LIVAN JEANS LTDA",
        "murano jeans": "LIVIAN JEANS LTDA",
        "mx": "CREACOES MX FASHION LTDA",
        "my fashion buyer": "My Fashion Buyer",
        "my story oficial": "My Story ",
        "myllena modas": "Nadicleia Cristiane Oliveira Silv Guaraná",
        "myti": "MYTI CONFECCOES LTDA",
        "myya fashion": "Juan Jose ",
        "n-bloom": "NAMINE CONFECCOES LTDA",
        "n-bloom atacado": "N-bloom Atacado",
        "n-bloom varejo": "NAMINE CONFECCOES LTDA",
        "nadri": "Nadri Confecções de Roupas LTDA",
        "nakepe": "Nakepe Creações Ltda",
        "nalva assessoria": "Nalva Assessoria",
        "namine": "CONFECÇÕES SA-O SA-GU LTDA",
        "namine - parana": "LTK CONFECCOES LTDA",
        "namine - rio grande do sul": "NAMINE CONFECCOES LTDA.",
        "namine - santa catarina": "L2V CONFECCOES LTDA",
        "nanaminze": "HELIAS DAI KIM",
        "nany borges moda feminina": "Eliane Cristina Borges Ferreira",
        "naos sport": "LIMA CONFECCOES FITNESS LTDA",
        "nari fashion": "CONFECCOES NARI FASHION LTDA",
        "nasmah": "Golden Style Vestuário LTDA",
        "nasmah filial": "Golden Style Vestuário LTDA",
        "natal 1": "DIAMANTES LINGERIE LTDA",
        "natal 3": "DIAMANTES LINGERIE LTDA",
        "nathalia aguiar": "Nathália Aguiar",
        "nega jeans": "NEGA COMERCIO VAREJISTA DE CONFECCOES LTDA",
        "nega jeans avelino": "Nega Comércio Varejista Confecções Ltda",
        "nega jeans jose avelino": "Nega Comércio Varejista Confecções Ltda",
        "nega jeans varejo": "NEGA COMERCIO VAREJISTA DE CONFECCOES LTDA",
        "nega maluca": "GEISA KELLY GOMES DE ARRUDA",
        "negally modas": "ALAERTES ALCI GONCALVES DIAS",
        "new gomone": "CREACOES NEW GOMONE LTDA",
        "new mire aviamentos": "NEW MIRE AVIAMENTOS LTDA",
        "new mire aviamentos - representante": "NEW MIRE AVIAMENTOS LTDA",
        "new umbi": "New Umbi Confecções Ltda",
        "nicky atacado": "DANIEL TOLA MAMANI",
        "nicoboco": "CONFECCOES DE ROUPAS GLOBAL CO. LTDA.",
        "nicoboco acessorios": "Nicoboco",
        "nicoboco chinelos": "Nicoboco",
        "nicoboco tenis couro": "Nicoboco",
        "nicoboco tenis lona": "Nicoboco",
        "nilce nannini": "Nilce Nannini",
        "nima": "NIMA COMERCIO DE ROUPAS, ACESSORIOS E CALCADOS LTDA",
        "niran confeccoes": "Niran Confeccoes",
        "nn atacados": "NN ATACADOS LTDA",
        "noirdeux": "CONFECCOES NOIR LTDA",
        "nono modas": "Noelma Cunha e Silva",
        "nova versao roupas": "NOVA VERSAO CONFECCOES LTDA",
        "nrd magazine": "CARVALHO COMERCIO DE VESTUARIO E ACESSORIOS EIRELI",
        "ntk": "NTK",
        "ntk loja ecko": "NTK CONFECCOES EIRELI",
        "ntk loja fatal": "NTK CONFECCOES EIRELI\t",
        "obzee": "Obzee",
        "ocasion": "CONFECCOES DE ROUPAS EG LTDA",
        "odete  assessoria de modas odete": "Odete  Assessoria De Modas Odete",
        "off store": "ALC Industria e Comércio de Roupas Ltda.   ",
        "ohvely": "BYUNG IK MIN",
        "okey 1": "Okey 1 ",
        "okey store - esc": "Okey",
        "okey store - sp": "Okey Store - SP",
        "okey store sp": "OKEY TECH",
        "okey tech": "OKEY TECH CONFECCOES LTDA",
        "olinda": "DIAMANTES LINGERIE LTDA",
        "opera kids": "Opera Kids",
        "opera kids programado": "FIKABEN CONFECCOES LIMITADA",
        "opera kids varejo": "SISNANDO LUIZ DE LUCA NETO",
        "oportunidades 1": "Oportunidades 1",
        "oportunidades 2": "Oportunidades 2",
        "optimist feirinha": "OPTIMIST INDUSTRIA COMERCIO IMPORTACAO E EXPORTACAO LTDA",
        "optimist jeans": "OPTIMIST INDUSTRIA COMERCIO IMPORTACAO E EXPORTACAO LTDA",
        "optimist representante": "OPTIMIST INDUSTRIA COMERCIO IMPORTACAO E EXPORTACAO LTDA",
        "other girls": "Msk Moda Ltda",
        "ousadia feminina": "Ousadia Feminina",
        "ousadia feminina - varejo": "Ousadia Feminina Moda Ltda",
        "outlet jv": "JOSE JONATAS VIEIRA FEITOSA",
        "outlet monlevade": "Wagner Gandra",
        "outlet vm": "Full Stop ",
        "outran": "DIAMANTES LINGERIE LTDA",
        "oxalis": "Oxalis indústria e comércio de roupas LTDA",
        "oxigenio modas": "GAIDO CONFECCOES LTDA",
        "p.a concept": "CONFECCOES P. A. CONCEPT LTDA",
        "padrina": "CONFECCOES BLOOMIN LTDA",
        "pagamento luis guilherme": "LUIS GUILHERME GONCALVES LEMES LTDA",
        "pagamento luiz carlos": "LUIZ CARLOS LEMES CPF 263.935.496-53",
        "paloma concept": "Fabio de Araujo Lima Ferreira Eireli",
        "paloma moda modesta": "PALOMA CLEMENTE CIPRIANO SILVA ",
        "pamela": "Pamela",
        "paran": "NOVA PARAN MODAS FEMININAS LTDA",
        "parauapebas": "DIAMANTES LINGERIE LTDA",
        "pargan": "COMERCIO DE ROUPAS MARANY LTDA",
        "pargan varejo": "desativo",
        "parnaiba": "DIAMANTES LINGERIE LTDA",
        "parnamirim": "DIAMANTES LINGERIE LTDA",
        "patacho": "A F de Lima LTDA",
        "patmos": "PATMOS MODA EVANGELICA E EXECUTIVA LTDA",
        "patmos atacado": "Patmos Moda Evangélica e Executiva Ltda Me",
        "patos": "DIAMANTES LINGERIE LTDA",
        "patricia brisolla": "Patricia Brisolla",
        "paulo afonso 1": "DIAMANTES LINGERIE LTDA",
        "paulo afonso 2": "DIAMANTES LINGERIE LTDA",
        "pca moda masculina": "PCA Moda Masculina",
        "pedido@millennium.com": "pedido@millennium.com",
        "penssy rodeo": "Penssy Rodeo",
        "peonia": "PEONIA MODAS LTDA. ­ EPP",
        "peptuchy & v10 jeans": "PEPTUCHY & V10 CONFECCOES LTDA",
        "per pochi": "CONFECCOES PETHIGA LTDA",
        "peran jeans": "MANOEL DE JESUS BEZERRA",
        "peri plus size": "MODAS PERI LTDA",
        "perola oriental": "Lkd Moda Feminina Ltda",
        "perola oriental bom retiro": "Perola Oriental Bom Retiro ",
        "petit enfant": "PETIT ENFANT CONFECCAO DE PECAS DO VESTUARIO LTDA",
        "pianeta | tq": "INTERMIX CONFECÇÕES DE ROUPAS LTDA",
        "picos": "DIAMANTES LINGERIE LTDA",
        "pieta": "PIETA CONFECCOES LTDA",
        "pieta loja acessorios": "PIETA CONFECCOES LTDA",
        "pieta vestipago": "Pietà VestiPago",
        "pigmento colecao": "CONFERSIL CONFECCOES LTDA",
        "pigmento pronta entrega": "CONFERSIL CONFECCOES LTDA",
        "pijamas lua cheia": "ANAA LUA COMERCIO DE PIJAMAS LTDA",
        "pistachio": "PISTACHIO CONFECCOES LTDA",
        "pistachio aimores": "Pistachio Aimorés",
        "pit bull -  pre venda goias": "Pit Bull",
        "pit bull - pre venda sp": "Pit Bull",
        "pit bull - pronta sp-go pf": "Pit Bull",
        "pit bull - pronta sp-go pj": "PIT BULL JEANS INDUSTRIA E COMERCIO DE CONFECCOES LTDA",
        "pit bull goias pf": "Pit Bull",
        "pit bull jeans goias pj": "PIT BULL JEANS IND. E COM. DE CONF. LTDA",
        "pit bull sao paulo pf": "Pit Bull",
        "pit bull sao paulo pj": "Pit Bull",
        "pj origem": "Paulo José",
        "pl@anilha.com": "pl@anilha.com",
        "planchet": "CONFECCOES PLANCHET EIRELI",
        "planet charm": "PLANET CHARM COMERCIO DE ARTIGOS DO VESTUARIO E ACESSORIOS LTDA",
        "plump": "PLUMP MODA PLUS SIZE",
        "poema": "SINFORIANO VERA ZARATE EIRELI",
        "poema hit": "SINFORIANO VERA ZARATE EIRELI ME",
        "polatof": "CONFECCOES POLATOF EIRELI",
        "pop shop": "GLAM FASHION CONFECCOES E COMERCIO EIRELI",
        "pora": "Comércio  de artigos do vestuário e acessórios",
        "practory": "SJT COMERCIO DE VESTUARIO FEMININO IMPORTACAO E EXPORTACAO LTDA",
        "praela": "Praela Confecções Ltda",
        "predilect's plus": "PREDILECTS MODAS LTDA",
        "presidente dutra": "DIAMANTES LINGERIE LTDA",
        "primicia confeccoes": "THIAGO ARNAUD LIMA",
        "priscila pires": "Priscila Pires",
        "priscila silva de oliveira": "Priscila Silva De Oliveira",
        "private label": "BOISE CONFECCOES LTDA",
        "prod": "manse",
        "prs jeans": "INDIGO RED INDUSTRIA E COMERCIO DE CONFECCOES EIRELI",
        "pty & v10 - pedidos": "PEPTUCHY & V10 CONFECCOES LTDA",
        "pury": "pury",
        "pury (matriz)": "pury (matriz)",
        "pury aimores": "LJK LOOK MODAS LTDA",
        "pury miller": "CONFECCOES PURY LTDA",
        "pury total": "CONFECCOES PURY LTDA",
        "pusco": "PERSIO ALEXANDR",
        "qbonita atacado": "QBONITA VESTIDOS DE FESTA LTDA",
        "qbonita varejo": "QBonita",
        "que coisa linda oficial": "QCL COMERCIO DE VESTUARIO EM GERAL LTDA",
        "quebela": "CONFECCOES QUEBELA LTDA",
        "quenn store": "Priscyla Pereira",
        "quisty": "QUISTY COMERCIAL EIRELI",
        "r&e confeccoes": "R&E CONFECCOES LTDA",
        "rafa brasil": "RB Comércio de Roupas LTDA",
        "rafael": "Rafael",
        "rafael cardoso": "RCR Clothing Original - Filial",
        "rafaela marca": "Rafaela Rabe",
        "raianne gonzaga naves": "Raianne Gonzaga Naves",
        "raphael": "Raphael",
        "rayra lima brand fitness": "RAYRA ALEIXO LIMA 07925578408  ",
        "rb store": "M. A. Bispo Confecções",
        "rcr original clothing": "RCR original Clothing",
        "reccorpus avenida fashion": "Recco, Recco & Cia Ltda",
        "reccorpus bom retiro": "RECCO RECCO & CIA LTDA",
        "reccorpus cianorte": "Recco, Recco & Cia Ltda",
        "reccorpus fabrica": "RECCO, RECCO E CIA LTDA",
        "reccorpus farroupilha": "RECCO RECCO & CIA LTDA",
        "reccorpus goiania": "RECCO RECCO & CIA LTDA",
        "reccorpus mega polo sp": "RECCO RECCO & CIA LTDA",
        "reccorpus mirassol": "RECCO RECCO & CIA LTDA",
        "reccorpus parana moda park": "RECCO RECCO & CIA LTDA",
        "reccorpus prime": "RECCO RECCO & CIA LTDA",
        "reccorpus vest sul": "Recco, Recco & Cia Ltda",
        "red line": "Red Line",
        "refugio": "JEANNE FERNANDES RIBEIRO 67434150300",
        "refugio modas": "JEANNE FERNANDES RIBEIRO 67434150300",
        "regina lucia de araujo": "Regina Lucia De Araujo",
        "reichert assessoria": "Reichert Assessoria",
        "rekim": "LRLJ MODAS LTDA",
        "renesse": "RENESSE CONFECCAO DE ROUPAS LTDA",
        "repete": "Repete Confecções Ltda.",
        "representacao joao eduardo": "Representação João Eduardo",
        "republica caipira": "C. ANDREIA DAMAZIO - CONFECCOES",
        "rery": "SAVASSI MODAS LTDA",
        "restore modas": "Regiane Alice da Luz",
        "restrito jeans": "WIBE CONFECCOES LTDA",
        "ricardo carvalho": "Ricardo Carvalho ",
        "ricardo kaial": "RICARDO KAIAL REPRESENTACOES LTDA",
        "ricca jeans": "RICCA JEANS CONFECCOES - EIRELI",
        "ricca jeans mega polo": "Ricca Jeans Confeccoes ",
        "ridana": "LORENCINI CONFECCOES LTDA",
        "rikka": "Rikka",
        "rita colato": "RITA DE CASSIA SOUTO COLATO LTDA",
        "riveli boutique": "Rafaela Riveli",
        "riviera clothing": "CUSTOMIZE INDUSTRIA DO VESTUARIO LTDA",
        "rj moda feminina": "RJ ATACADO DO BRAS LTDA",
        "rl bijux acessorios": "Rl bijux acessórios Ltda",
        "rl modas": "RL MODDAS LTDA",
        "roberto": "Roberto",
        "roberto pasold": "Roberto Pasold",
        "rodrigo prado": "Rodrigo Prado",
        "roma joias": "Roma Joias",
        "romaleo jeans": "MATEUS E SILVA CONFECÇÕES LTDA. ME.",
        "romeriton paulo gomes": "ROMERITON PAULO GOMES CONFECCOES",
        "ronega jeans": "Ronega Jeans LTDA",
        "rosa aviamentos": "ROSA AVIAMENTOS EIRELI",
        "rosa chick": "ROSA CHICK IND. E COM. CONFECCOES EIRELI",
        "rosa fina": "DROPE COMÉRCIO DE ROUPAS LTDA - EPP",
        "rosa fina (caninde)": "DROPE COMÉRCIO DE ROUPAS LTDA - EPP",
        "rosa fina (mega polo)": "DROPE COMÉRCIO DE ROUPAS LTDA - EPP",
        "rosa fina deposito 02": "Rosa fina",
        "rosa fina mega polo -03": "Rosa fina Mega Polo",
        "rosa fina presence homologacao": "Rosa Fina Presence Homologacao",
        "rosa lua atacado": "ROSA LUA ATACADO LTDA",
        "rosalina": "Linamur oficial",
        "rosana": "Rosana",
        "rosangela": "Rosangela",
        "rosebella": "ROSEBELLA ATACADO LTDA",
        "rosie lingerie": "Rosie Lingerie Kaio Mendes Industria LTDA",
        "roze monteiro": "Roze Monteiro",
        "rs assessoria": "RENAN SANTOS SILVA 36990170875",
        "rubia": "Rubia   ",
        "rubicon modas": "RUBICON MODAS LTDA",
        "s i e g": "SIEG SPORTS LTDA",
        "s. e moda plus size": "INDUSTRIA DE CONFECCOES S.E MODA PLUS SIZE LTDA",
        "s.a fitness": "65.976.576 SERGIO CICERO MORENO TORRES",
        "s.a.b. modas feminina": "65.849.602 BRENDA VANEZA CHAMBI ANTINAPA",
        "saga mais": "S G COMMERCE",
        "salvador": "DIAMANTES LINGERIE LTDA",
        "salvadore plus size": "CONFECCOES SALVADORE LTDA",
        "sam jow": "Adan Alvarez Huchani",
        "sam modas": "ADAN ALVAREZ HUCHANI",
        "sammy t-shirts​": "SAMARA BARROS DOS SANTOS CONFECCOES",
        "sandy": "SANDY MODA PLUS LTDA",
        "sangue de peao": "Elisangela",
        "sania maria": "Sania Maria",
        "sanny lingerie": "Sanny Confecções Femininas S A",
        "sanreed": "WIBE CONFECCOES EIRELI",
        "sanreed varejo": "WIBE CONFECCOES EIRELI\t",
        "santa ines": "DIAMANTES LINGERIE LTDA",
        "santa lu": "MODO SANTO CONFECCOES EIRELI",
        "santa prata": "Santa Prata",
        "santa prata  - ar": "ARYA COMERCIAL",
        "santa prata - iq": "IQUIRIRIM COMERCIAL",
        "santa prata - oc": "OCTTO COMERCIO E IMPORTACAO LTDA",
        "santa prata - p8": "PORTAL 8 COMERCIO E IMPORTACAO LTDA",
        "santa prata - sh": "SANTA HARMONIA COMERCIO E IMPORTACAO LTDA",
        "santa rita": "DIAMANTES LINGERIE LTDA",
        "santarem": "DIAMANTES LINGERIE LTDA",
        "santo vicio fabrica": "Santo Vício",
        "santo vicio filial 3": "Santo Vício",
        "santo vicio filial 4": "Santo Vício",
        "santo vicio mega polo": "Santo Vício",
        "santo vicio porto bras": "Santo Vício",
        "sao luis 1": "DIAMANTES LINGERIE LTDA",
        "sao luis 2": "DIAMANTES LINGERIE LTDA",
        "sao luis 3": "DIAMANTES LINGERIE LTDA",
        "sao luis 4": "DIAMANTES LINGERIE LTDA",
        "sao luis 6": "DIAMANTES LINGERIE LTDA",
        "sapporo": "Sapporo",
        "sara e mari": "Sara e Mari",
        "sard": "SARD INDUSTRIA E COMERCIO DE ROUPAS LTDA",
        "saue beach wear": "CYELLE BEACH WEAR CONFECCAO LTDA",
        "savannah brand": "ESJ CONFECCOES DO VESTUARIO LTDA",
        "sawary": "Sawary Confeccoes ltda",
        "sawary representantes": "Sawary Representantes ",
        "scera": "SCERA MODA FEMININA LTDA",
        "scera filial": "SCERA MODA FEMININA LTDA",
        "sdb": "IND COM DE ROUPAS SEDANBI LTDA EPP",
        "sedanbi": "Sedanbi",
        "seiss & deiss": "SEISS CONFECCOES DE ROUPAS EIRELI",
        "sejakayla": "SEJAKAYLA",
        "select new style": "Andrew Valentim dos santos",
        "sence": "MODAS SENCE LTDA",
        "sensual fetiche": " VALERIO AVELINO CARVALHO",
        "sessi": "MOLLY FASHION MODAS LTDA",
        "shalen modas": "Shalen Modas LTDA",
        "shanes curves maringa": "SHANES COMERCIO DE CONFECCOES LTDA",
        "shanes fashion": "CONFECCOES SHANES LTDA ",
        "shante fashion": "SHANTE FASHION COMERCIO E CONFECCOES LTDA",
        "she brand": "S.G. DE ANDRADE CONFECCOES",
        "show me": "KOKOLA CONFECCOES E COMERCIO DE ROUPAS LTDA",
        "showroom": "HELIAS DAI KIM",
        "shyros jeans": "Confecções Shiroma LTDA",
        "sigui atacado": "Confecções Josigmoni LTDA",
        "silvania carneiro de jesus": "Silvania Carneiro De Jesus",
        "silveira": "Silveira",
        "simbolo fashion": "J C C RAMOS",
        "simone": "HELIAS DAI KIM",
        "simple life": "SIMPLE LIFE CONFECCOES LTDA",
        "sis's moda": "Wilia Chaves Pereira",
        "sisal jeans": "N A Almendra Goffert Confeccoes LTDA",
        "skenn brusque": "COMERCIO DE ROUPAS MARANY LTDA",
        "skenn farroupilha": "COMERCIO DE ROUPAS MARANY LTDA",
        "skenn homol": "skenn homol",
        "skenn maringa": "COMERCIO DE ROUPAS MARANY LTDA",
        "skenn miller": "Skenn Miler ",
        "skenn rio preto": "COMERCIO DE ROUPAS MARANY LTDA",
        "skyler acessorios": "GABY PAOLA CONDO TUNQUE",
        "skyline assessoria de moda": "Skyline Assessoria de Moda",
        "sline spoorte": "Billion fit Conf. Ltda",
        "smart hub": "Smart Hub",
        "sml modas": "03.009-010SMEL COMERCIO E ACESSORIOS DE VESTUARIOS LTDA",
        "sml pacote": "SML PACOTE",
        "sn acessorios": "YISELA CRUZ YUCRA",
        "snapper": "SNAPPER STREET WEAR LTDA",
        "sol e energia": "SOL E ENERGIA MODAS LTDA",
        "sol jeans": "J. F. B DA SILVA COMERCIO DE ROUPAS",
        "solange": "Solange",
        "solange esteves": "Solange Esteves",
        "solange rocha": "Solange Rocha",
        "sori": "JEH CONFECCOES EIRELI",
        "soror clothing co.": "ANA PAULA DE ALENCAR MARTINS 06168889965 ",
        "sp kids representacoes": "SP KIDS REPRESENTACOES COMERCIAIS LTDA",
        "spot shoes - barao": "RAFAEL DANIELIAN",
        "spot shoes - bom retiro": "S.S. CALÇADOS E ACESSÓRIOS EIRELI",
        "spot shoes - bras": "Rafael Danielian",
        "ssang bang wool": "CONFECCOES SSANG BANG WOOL LTDA",
        "ste fashion": "CHOCOS ARTIGOS DO VESTUARIO EIRELI",
        "stefani": "ADELA OLGA PRADO CASTRO COSTURAS",
        "stefanie franco": "ZULMA VERDUGUEZ TRUJILLO",
        "stop shop brusque": "RECCO, RECCO E CIA LTDA",
        "stranger": "STRANGER COMPANY CONFECCOES LTDA",
        "strelisse": "Strelisse Industria de Confecção de Moda Íntima Ltda",
        "stun 2020": "JOUNIEH COM IMP EXP",
        "sub way store": "SUB WAY COMERCIO E CONFECCOES LTDA",
        "sued t-shirt": "Washington luis carvalho Silva",
        "sueli": "Sueli ",
        "sueli aparecida nogueira": "Sueli Aparecida Nogueira",
        "sunweek": "Sunweek Beach Wear LTDA",
        "super bonita": " L E V DA SILVA NERIS ROUPAS",
        "super kids": "SUPER KIDS GV LTDA",
        "surf center": "Surf Center Indústria e Comércio de Confecção LTDA",
        "susan zheng": "Z COMERCIO DE ROUPAS EIRELI",
        "susi aura moda": "MIGUEL A. MAMANI ADUVIRI",
        "t-shirts fashion": "SM T-SHIRTS FASHION VESTUARIOS E ACESSORIOS LTDA",
        "taju": "TAVARES - COMERCIO DE CONFECCOES & SERVICOS LTDA",
        "taju - pedidos": "Tavares Comercio",
        "talgui": "TALGUI CONFECCOES DE ROUPAS LTDA",
        "talita": "HELIAS DAI KIM",
        "talita elisabete santos da silva": "Talita Elisabete Santos Da Silva",
        "tango fantasias": "INDUSTRIA E COMERCIO TANGO FANTASIAS LTDA.",
        "tania gouvea": "Tania Gouvea",
        "tanker jeans": "LEANDRO RICARDO G SOARES E SILVA",
        "tdc revenda cpf": "TEMPO DE CRIANCA MODA INFANTIL LTDA",
        "team basic": "Team Basic Varejo ",
        "teaser all style": "TEASER ALL STYLE COMERCIO DE ROUPAS E ACESSORIOS LTDA",
        "tee bella": "Tee Bella",
        "tee fashion": "TEE FASHION ARTIGOS DO VESTUARIO EIRELI",
        "tee fashion filial": "TEE FASHION ARTIGOS DO VESTUARIO EIRELI",
        "tee fashion newmall": "Leonardo",
        "televendas 2": "DIAMANTES LINGERIE LTDA",
        "televendas 4": "DIAMANTES LINGERIE LTDA",
        "televendas 5": "DIAMANTES LINGERIE LTDA",
        "televendas 7": "DIAMANTES LINGERIE LTDA",
        "televendas 8": "DIAMANTES LINGERIE LTDA",
        "tempo de crianca": "TEMPO DE CRIANCA MODA INFANTIL LTDA",
        "teresina 3": "DIAMANTES LINGERIE LTDA",
        "teresina 4": "DIAMANTES LINGERIE LTDA",
        "teresina 5": "DIAMANTES LINGERIE LTDA",
        "terra mae": "TERRA - MAE INDUSTRIA E COMERCIO DE CONFECCOES LTDA",
        "terraza closet": "Gabriele Afonso de Lima",
        "teste": "TESTE",
        "testee umm": "Testee Umm",
        "tgr denim": "TGR Denim",
        "thas": "Thas   ",
        "the plus": "ADAGIO STORE LTDA",
        "therapia feminina": "JEANNE FERNANDES MODAS LTDA",
        "threesix 3/6": "THREESIX CONFECCOES LTDA",
        "tiny": "TINY",
        "tl clothes": "Talissa Loreto",
        "tn modas": "Tn Modas LTDA",
        "tnw jeans": "TNW CONFECCOES LTDA",
        "toda linda": "TODA LINDA COMERCIAL DO VESTUARIO LTDA",
        "todas dyvas": "Evelyn Herrera",
        "tomany": "CONFECCOES DE ROUPAS TOMANY LTDA",
        "tonny show fashion": "Tonny Show Fashion",
        "top orange": "YXM CONFECÇÕES LTDA",
        "top representacoes": "Top Representações",
        "toque secreto lingerie": "Toque Secreto Roupas Intimas LTDA​",
        "traffos atacado": "Traffos Confecções LTDA",
        "trama jeans": "LIZT - TRAMA INDUSTRIA E COMERCIO DE CONFECCOES LTDA",
        "transby shop": "TRANSBY SHOP COMERCIO DE CONFECCOES LTDA",
        "tratto jeans": "ZEAIT INDUSTRIA E COMERCIO DE CONFECCOES LTDA",
        "trendy": "Trendy",
        "tricomix": "TRICOMIX INDUSTRIA E COMERCIO DE CONFECCOES EIRELI",
        "tricomix bom retiro": "TRICOMIX INDUSTRIA E COMERCIO DE CONFECCOES EIRELI",
        "tricomix mega": "TRICOMIX INDUSTRIA E COMERCIO DE CONFECCOES EIRELI",
        "tricomixpolo": "TRICOMIX INDUSTRIA E COMERCIO DE CONFECCOES EIRELI",
        "tricotez": "TRICOTEZ",
        "tricotez mega": "Tricotez Mega",
        "tricotez total": "TRICOTEZ",
        "trimix": "CONFECCOES TRIMIX LTDA",
        "trimix  bom retiro": "CONFECCOES TRIMIX LTDA",
        "trimix bras": "CONFECCOES TRIMIX LTDA",
        "trindade": "TRINDADE FASHION EIRELI",
        "tropical brasil": "TROPIMAX INDUSTRIA E COMERCIO DE CALCADOS LTDA",
        "tropical color": "Sheyla Mireya Sejas Cuaquira",
        "true jhess": "Jhessica De Godoi Brando",
        "ttng": "TAUNTING BRAND COMERCIO E VAREJO LTDA",
        "ttng varejo": "TAUNTING BRAND COMERCIO E VAREJO LTDA",
        "tuba plus size": "CONFECCOES TUBA LTDA - EPP",
        "tulipeira": "R.C. LOURENZON MODAS",
        "tutti sposa": "MON CHERI BRASIL ALTA COSTURA LTDA",
        "tutto store": "CONFECCOES TUTTO LTDA.",
        "tyfhanie  airton assessoria": "Tyfhanie  Airton Assessoria",
        "uap representacoes": "UAP REPRESENTACOES LTDA",
        "uezz": "SML CONFECÇÕES ATACADISTA LTDA",
        "unbrand": "LINE PLUS MARKET PLACE LTDA",
        "urban race": "Urban Race",
        "use buh": "COMERCIO DE ROUPAS MARANY LTDA",
        "use closet da amel": "Ameliane De Almeida",
        "usuario de suporte vesti": "Usuário de suporte Vesti",
        "uyu": "PURPURIN CONFEÇÕES LTDA",
        "uzze cruz": "Katherine Soledad",
        "v.azevedo": "Vazevedo",
        "v.e.m": "Vida Energia Movimento Industria e Comercio de Confeccoes LTDA",
        "v.r.modas.plus": "Vr Moda Plus Size LTDA",
        "valentina sirrah": "VALENTINA SIRRAH CONFECCOES LTDA",
        "valentina sirrah cianorte": "Valentina Sirrah Confecções LTDA",
        "valentins fashion": "JANAINA DE MEDEIROS VALENTIM",
        "valeria c giovannetti": "Valeria C Giovannetti",
        "vanessa freitas pereira": " Vanessa Freitas Pereira",
        "varejo": "Vesti Treinamentos",
        "varejo - john cunningham": "John Cunningham",
        "veln": "Veln Alberto ",
        "venoro": "VENORO COMERCIO, IMPORTACAO E INDUSTRIA DE ARTIGOS DE BIJUTERIAS E VESTUARIO LTDA",
        "venus modas": "Maria Elisa Mendes",
        "vera assessoria": "Vera Assessoria",
        "vera lucia": "Vera Lucia",
        "versally lingerie": "VERSALLY INDUSTRIA DE CONFECCOES LTDA",
        "veste boy": "MARIA MAYARA SOARES DE LIMA",
        "veste vegana": "Priscila Bueno da Silva",
        "vesti": "VESTI",
        "vesti light": "Vesti Light",
        "vesti modas": "OSCAR EDUARDO PENA MENDEZ",
        "vesti treinamento filial": "É uma razão",
        "vesti treinamentos 266": "VESTITREINAMENTOS",
        "vesti varejo": "Teste Projeto Bia",
        "vestidoteca": "LUW CONFECCOES LTDA",
        "vestidoteca varejo": "LUW CONFECCOES LTDA",
        "vestipago cnpj teaser": "TEASER ALL STYLE COMERCIO DE ROUPAS E ACESSORIOS LTDA",
        "vevantagens": "V Vantagens ",
        "vg moda evangelica": "Vanir Gabriel Maurcio",
        "vg store clothes": "Vanessa Galvani",
        "vibak moda feminina": "VITTORIA BACCHI CONFECCOES E COMERCIO DE ROUPAS EIRELI",
        "vibe teen": "ESTACAO KIDS MODA INFANTIL LTDA",
        "victoria fashion": "M.V. INDUSTRIA E COMERCIO DE CONFECCOES EIRELI",
        "vida bela": "Samir Abrao Bassitt Cia Ltda",
        "vida bela bras": "CASSIO PIOVESAN BASSITT VESTUARIO",
        "vida marinha atacado": "Vida Marinha Atacado ",
        "vida vici": "VIDA VICI MODAS LTDA",
        "vie libre": "Bylsa Santos De Oliveira",
        "viknstore": " VIKNSTORE COMERCIO DE ROUPAS LTDA",
        "vila sol fortaleza": "VIA SOL MODA PRAIA - INDUSTRIA DE CONFECCOES LTDA",
        "vila sol sao paulo": "VIA SOL MODA PRAIA - INDUSTRIA DE CONFECCOES LTDA",
        "vila sol varejo": "VIA SOL MODA PRAIA - INDUSTRIA DE CONFECCOES LTDA",
        "villa forte jeans": " Villa Forte Confecções Ltda",
        "villon jeans": "Villon Jeans",
        "villon jeans fashion": "Trama Villon Indústria De Confecções Ldta",
        "villon jeans rota da moda": "Trama Villon Indústria De Confecções Ldta",
        "vinicius pereira": "Vinicius Pereira",
        "vintage atacadista": "Vintage Atacadista Ltda",
        "vionet": "E. F. DA SILVA COMERCIO DE VESTUARIO",
        "vionix": "CONFECCOES VIONIX LTDA",
        "viotto": "UZZE VIOTTO CONFECCOES LTDA",
        "vip fashion": "VIP FASHION INDUSTRIA DE CONFECCOES LTDA",
        "vip fashion maraponga": "Vip Fashion Indústria de confecções Ltda",
        "vip fashion shopping ceara": "Vip Fashion Indústria de confecções Ltda",
        "vip fashion shopping metro": "Vip Fashion Indústria de confecções Ltda",
        "virou moda": "VIROU MODA CONFECCOES LTDA",
        "vistamy jeans": "Vinicius da Silva Bezerra",
        "visual+": "BRUNO & MARIA MODAS LTDA",
        "vitor azul assessoria": "Vitor Azul Assessoria",
        "vitoria fashion": "VITORIA FASHION COMERCIO DE ROUPAS E CONFECCOES EM GERAL LTDA",
        "vitral": "J Y KIM CONFECCOES LTDA",
        "vivielle": "Yone Mamani Medina",
        "vn11": "VINTE E NOVE ONZE CONFECCOES EIRELI",
        "vn11 aimores": "VINTE E NOVE ONZE CONFECCOES LTDA",
        "vocco": "MODAS VOCCO LTDA",
        "voce nos move": "31987567391",
        "vogabox": "SEXY COOKIE CONFECCOES LTDA",
        "volpy girls": "Volpy Girls",
        "vout": "Vout Ind e Comércio de Roupas e Acessórios Ltda​",
        "vov": "MODAS VOV LTDA",
        "vystu": "LOOK STUDIO INDUSTRIA E COMERCIO DE CONFECCOES - EIRELI",
        "wa baby": "WA BABY INDUSTRIA DE CONFECCOES LTDA",
        "wagner santos": "Wagner Santos",
        "wasafdy": "Modas Wasafdy",
        "wave core": "ALEXSANDRO DA SILVA LEMOS LTDA",
        "weekend": "CONFECCOES HANS LTDA",
        "wendell ribeiro dias": "Wendell Ribeiro Dias",
        "wi fi": "Wi Fi",
        "wibe confeccoes": "Fiest Jeans - Filial Atacado",
        "winnie modas": "Winnie Confecções ltda",
        "wish brand": "Wish Brand",
        "wool line": "WOOL LINE CONFECCOES EIRELI",
        "worldstar lingerie ​": "WORLDSTAR INDUSTRIA E COMERCIO DE CONFECCOES LTDA​",
        "wotson alves batista": "Wotson Alves Batista",
        "wyllara": "Wyllara",
        "wyller wm representaes": "Wyller Wm Representaes",
        "yara esteves": "Yara Esteves",
        "yegrin": "YEGRIN MODAS LTDA",
        "yegrina": "YEGRINA CONFECCOES DE ROUPAS LTDA",
        "yoo moda grande": "CONFECCOES YOO LTDA",
        "yoyo": "CONFECCOES YO YO FASHION LTDA",
        "ytcom": "Ytcom Confeccoes e Comercio LTDA",
        "yunico": "CONFECCOES YUNICO LTDA",
        "yunire": "K. H. KIM - CONFECCOES",
        "yzzy": "JULIETA PINTO PAULINO DE MEDEIROS",
        "zafira": "Zafira Atacado LTDA",
        "zarak": "J M KWAK CONFEÇÕES LTDA",
        "zeros confeccoes": "ZEROS CONFECCOES LTDA",
        "zk brand": "ZK BRAND LTDA",
        "zod store": "ZOGA COMERCIO DE VESTUARIO E ACESSORIOS LTDA",
        "zoe sport": "CHRISTIAM RAISSA DOS SANTOS",
        "zua style apucarana": " ZUA STYLE COMERCIO DE ARTIGOS DO VESTUARIO APUCARANA LTDA.",
        "zua style atacado maringa": "ZUA STYLE ATACADO DO VESTUARIO MARINGA LTDA",
        "zua style maringa": "ZUA STYLE CONFECCAO MARINGA LTDA",
        "zua style matriz": "ZUA STYLE CONFECCAO DO VESTUARIO APUCARANA LTDA",
        // overrides manuais (planilha CC Starkbank - Walid) — sobrescrevem companies_data.json
        "alcance jeans": "ALC INDUSTRIA E COMERCIO DE ROUPAS LTDA",
        "alcance jeans nova": "ALC INDUSTRIA E COMERCIO DE ROUPAS LTDA",
        "anne blanc": "AMANDA CONFECCOES LTDA",
        "arary": "ARARY COMERCIO DE TECIDOS LTDA",
        "barraca do willinha": "THAMIRIS ALTEA VIEIRA",
        "begkids": "ISABELA CARINY SALES MADEIRO - ME",
        "bella donna": "BELLA DONNA MODA BRAS ARTIGOS DO VESTUARIO LTDA",
        "erilluz jeans": "GILDA DE LIRA PEIXOTO",
        "evian": "LHB CONFECCOES DE ROUPAS LTDA",
        "ezee": "EZEE CONFECCOES DE ROUPAS LTDA",
        "imporio fitness": "ALINE LAYS DE LIMA SILVA TORRES - ME",
        "incentive moda": "CONFECCOES INCENTIVE LTDA",
        "kelly rodrigues": "RK STORE LTDA",
        "mafia fitness": "LIMA CONFECCOES FITNESS LTDA",
        "maria lima": "RD CONFECCOES DE ROUPAS LTDA",
        "maria lima santa cruz": "RD CONFECCOES DE ROUPAS LTDA",
        "missmel": "GILMA MARIA SIMAO LTDA",
        "nicky atacado": "DANIEL TOLA MAMANI",
        "nono modas": "NOELMA CUNHA MENEZES",
        "oxigenio modas": "GAIDO CONFECCOES LTDA",
        "patacho": "A F DE LIMA LTDA",
        "patachosn": "A F DE LIMA LTDA",
        "petit enfant": "CORPORATIVO TACI LTDA",
        "sedanbi": "COMERCIO E CONFECCOES DE ROUPAS S H LTDA",
        "tee fashion": "TEE FASHION ARTIGOS DO VESTUARIO LTDA",
        "vistamy": "VINICIUS DA S BEZERRA LTDA",
        "zeros confec": "ZEROS CONFECCOES LTDA"
    };
    function norm(s){
        return String(s||"").toLowerCase().trim()
            .normalize("NFD").replace(/[̀-ͯ]/g,"");
    }
    var map = {};
    for (var k in raw) map[norm(k)] = raw[k];
    return { get:function(name){return map[norm(name)]||""} };
})();
