window.DADOS = {
  "gerado_em": "2026-09-08T15:41:15.259Z",
  "hoje": "2026-09-08",
  "medindo_desde": "2026-07-24T17:20:05.000Z",
  "apps_desde": "2026-08-11T18:28:02.542Z",
  "auto_publica_desde": "2026-08-10",
  "criterio": {
    "produtos_semana": 2,
    "dias_parada": 7,
    "janela_dias": 7,
    "semanas": 12
  },
  "kpis": {
    "liberadas": 19,
    "ativas": 4,
    "usando": 11,
    "nunca_usaram": 8,
    "paradas": 3,
    "com_conta": 11,
    "contas": 10,
    "produtos_total": 415,
    "produtos_7d": 67,
    "descricoes_total": 543,
    "total_estimado": true
  },
  "marcas": [
    {
      "slug": "nicoboco",
      "nome": "Nicoboco",
      "arquetipo": "explorador",
      "tem_conta": true,
      "email": "nicoboco.shop@nicoboco.com.br",
      "produtos": 176,
      "estimado": false,
      "produtos_7d": 42,
      "ativa": true,
      "acessos": 62,
      "buscas": 322,
      "descricoes": 225,
      "envios": 251,
      "primeiro": "2026-08-10T19:02:35.392Z",
      "ultimo": "2026-09-07T16:09:00.194Z",
      "dias": 0
    },
    {
      "slug": "amiska",
      "nome": "Amiska",
      "arquetipo": "sabio",
      "tem_conta": true,
      "email": "missmilliebr@gmail.com",
      "produtos": 82,
      "estimado": true,
      "produtos_7d": 10,
      "ativa": true,
      "acessos": 10,
      "buscas": 55,
      "descricoes": 71,
      "envios": 64,
      "primeiro": "2026-07-28T18:41:18.639Z",
      "ultimo": "2026-09-08T13:36:16.792Z",
      "dias": 0
    },
    {
      "slug": "opera-kids",
      "nome": "Ópera Kids",
      "arquetipo": "inocente",
      "tem_conta": true,
      "email": "contato@operakids.com.br",
      "produtos": 81,
      "estimado": false,
      "produtos_7d": 1,
      "ativa": false,
      "acessos": 74,
      "buscas": 139,
      "descricoes": 133,
      "envios": 118,
      "primeiro": "2026-07-28T11:47:18.529Z",
      "ultimo": "2026-09-02T17:11:58.593Z",
      "dias": 5
    },
    {
      "slug": "petit",
      "nome": "Petit",
      "arquetipo": "inocente",
      "tem_conta": true,
      "email": "anderson@mundotaci.com.br",
      "produtos": 43,
      "estimado": true,
      "produtos_7d": 0,
      "ativa": false,
      "acessos": 0,
      "buscas": 0,
      "descricoes": 14,
      "envios": 14,
      "primeiro": "2026-08-27T10:08:32.689Z",
      "ultimo": "2026-08-31T19:02:37.837Z",
      "dias": 7
    },
    {
      "slug": "monnika-marikinha",
      "nome": "Monnika Marikinha",
      "arquetipo": "amante",
      "tem_conta": true,
      "email": "monnikamarikinhaloja@gmail.com",
      "produtos": 11,
      "estimado": false,
      "produtos_7d": 6,
      "ativa": true,
      "acessos": 2,
      "buscas": 1,
      "descricoes": 11,
      "envios": 11,
      "primeiro": "2026-08-06T14:16:43.085Z",
      "ultimo": "2026-09-03T17:32:55.872Z",
      "dias": 4
    },
    {
      "slug": "andressa-vesti",
      "nome": "Andressa Vesti",
      "arquetipo": "rebelde",
      "tem_conta": true,
      "email": "andressavazpinto@gmail.commx",
      "produtos": 9,
      "estimado": false,
      "produtos_7d": 0,
      "ativa": false,
      "acessos": 27,
      "buscas": 60,
      "descricoes": 21,
      "envios": 12,
      "primeiro": "2026-08-10T16:01:03.796Z",
      "ultimo": "2026-08-20T11:06:21.271Z",
      "dias": 19
    },
    {
      "slug": "kauly",
      "nome": "Kauly",
      "arquetipo": "governante",
      "tem_conta": true,
      "email": "marketing@kauly.com.br",
      "produtos": 8,
      "estimado": false,
      "produtos_7d": 8,
      "ativa": true,
      "acessos": 2,
      "buscas": 7,
      "descricoes": 11,
      "envios": 9,
      "primeiro": "2026-09-02T19:08:41.700Z",
      "ultimo": "2026-09-08T15:00:22.895Z",
      "dias": 0
    },
    {
      "slug": "optimist-jeans",
      "nome": "Optimist Jeans",
      "arquetipo": "governante",
      "tem_conta": true,
      "email": "ecommerce@optimistjeans.com.br",
      "produtos": 3,
      "estimado": false,
      "produtos_7d": 0,
      "ativa": false,
      "acessos": 3,
      "buscas": 3,
      "descricoes": 4,
      "envios": 5,
      "primeiro": "2026-08-07T13:23:05.929Z",
      "ultimo": "2026-08-07T14:55:31.596Z",
      "dias": 32
    },
    {
      "slug": "optimist-feirinha",
      "nome": "Optimist Feirinha",
      "arquetipo": "",
      "tem_conta": true,
      "email": "ecommerce@optimistjeans.com.br",
      "produtos": 2,
      "estimado": false,
      "produtos_7d": 0,
      "ativa": false,
      "acessos": 0,
      "buscas": 1,
      "descricoes": 0,
      "envios": 2,
      "primeiro": "2026-08-07T13:33:14.591Z",
      "ultimo": "2026-08-07T14:33:01.598Z",
      "dias": 32
    },
    {
      "slug": "anne-blanc",
      "nome": "Anne Blanc",
      "arquetipo": "",
      "tem_conta": false,
      "email": "",
      "produtos": 0,
      "estimado": false,
      "produtos_7d": 0,
      "ativa": false,
      "acessos": 0,
      "buscas": 0,
      "descricoes": 0,
      "envios": 0,
      "primeiro": "",
      "ultimo": "",
      "dias": null
    },
    {
      "slug": "demissy",
      "nome": "DeMissy",
      "arquetipo": "",
      "tem_conta": true,
      "email": "comercial.danque@gmail.com",
      "produtos": 0,
      "estimado": false,
      "produtos_7d": 0,
      "ativa": false,
      "acessos": 0,
      "buscas": 0,
      "descricoes": 0,
      "envios": 0,
      "primeiro": "",
      "ultimo": "",
      "dias": null
    },
    {
      "slug": "gitaa",
      "nome": "Gitaa",
      "arquetipo": "",
      "tem_conta": false,
      "email": "",
      "produtos": 0,
      "estimado": false,
      "produtos_7d": 0,
      "ativa": false,
      "acessos": 0,
      "buscas": 0,
      "descricoes": 0,
      "envios": 0,
      "primeiro": "",
      "ultimo": "",
      "dias": null
    },
    {
      "slug": "kauly-varejo",
      "nome": "Kauly varejo",
      "arquetipo": "",
      "tem_conta": false,
      "email": "",
      "produtos": 0,
      "estimado": false,
      "produtos_7d": 0,
      "ativa": false,
      "acessos": 0,
      "buscas": 0,
      "descricoes": 0,
      "envios": 0,
      "primeiro": "",
      "ultimo": "",
      "dias": null
    },
    {
      "slug": "luciana-pais",
      "nome": "Luciana Pais",
      "arquetipo": "governante",
      "tem_conta": false,
      "email": "",
      "produtos": 0,
      "estimado": true,
      "produtos_7d": 0,
      "ativa": false,
      "acessos": 0,
      "buscas": 0,
      "descricoes": 0,
      "envios": 0,
      "primeiro": "",
      "ultimo": "2026-09-03T15:12:18.694Z",
      "dias": 5
    },
    {
      "slug": "murano",
      "nome": "Murano",
      "arquetipo": "",
      "tem_conta": false,
      "email": "",
      "produtos": 0,
      "estimado": false,
      "produtos_7d": 0,
      "ativa": false,
      "acessos": 0,
      "buscas": 0,
      "descricoes": 0,
      "envios": 0,
      "primeiro": "",
      "ultimo": "",
      "dias": null
    },
    {
      "slug": "murano-filial",
      "nome": "Murano filial",
      "arquetipo": "",
      "tem_conta": false,
      "email": "",
      "produtos": 0,
      "estimado": false,
      "produtos_7d": 0,
      "ativa": false,
      "acessos": 0,
      "buscas": 0,
      "descricoes": 0,
      "envios": 0,
      "primeiro": "",
      "ultimo": "",
      "dias": null
    },
    {
      "slug": "stefani",
      "nome": "Stefani",
      "arquetipo": "",
      "tem_conta": false,
      "email": "",
      "produtos": 0,
      "estimado": false,
      "produtos_7d": 0,
      "ativa": false,
      "acessos": 0,
      "buscas": 0,
      "descricoes": 0,
      "envios": 0,
      "primeiro": "",
      "ultimo": "",
      "dias": null
    },
    {
      "slug": "trimix",
      "nome": "Trimix",
      "arquetipo": "heroi",
      "tem_conta": true,
      "email": "salomon@trimix.com.br",
      "produtos": 0,
      "estimado": false,
      "produtos_7d": 0,
      "ativa": false,
      "acessos": 15,
      "buscas": 55,
      "descricoes": 53,
      "envios": 0,
      "primeiro": "2026-08-04T14:28:52.117Z",
      "ultimo": "2026-09-01T13:07:03.363Z",
      "dias": 7
    },
    {
      "slug": "ttng",
      "nome": "TTNG",
      "arquetipo": "",
      "tem_conta": false,
      "email": "",
      "produtos": 0,
      "estimado": false,
      "produtos_7d": 0,
      "ativa": false,
      "acessos": 0,
      "buscas": 0,
      "descricoes": 0,
      "envios": 0,
      "primeiro": "",
      "ultimo": "",
      "dias": null
    }
  ],
  "semanas": [
    {
      "inicio": "2026-06-22",
      "fim": "2026-06-28",
      "produtos": 0,
      "ativas": 0,
      "usaram": 0,
      "cadastros": 0,
      "novos": 0
    },
    {
      "inicio": "2026-06-29",
      "fim": "2026-07-05",
      "produtos": 0,
      "ativas": 0,
      "usaram": 0,
      "cadastros": 0,
      "novos": 0
    },
    {
      "inicio": "2026-07-06",
      "fim": "2026-07-12",
      "produtos": 0,
      "ativas": 0,
      "usaram": 0,
      "cadastros": 0,
      "novos": 0
    },
    {
      "inicio": "2026-07-13",
      "fim": "2026-07-19",
      "produtos": 0,
      "ativas": 0,
      "usaram": 0,
      "cadastros": 3,
      "novos": 3
    },
    {
      "inicio": "2026-07-20",
      "fim": "2026-07-26",
      "produtos": 0,
      "ativas": 0,
      "usaram": 0,
      "cadastros": 5,
      "novos": 2
    },
    {
      "inicio": "2026-07-27",
      "fim": "2026-08-02",
      "produtos": 13,
      "ativas": 2,
      "usaram": 2,
      "cadastros": 5,
      "novos": 0
    },
    {
      "inicio": "2026-08-03",
      "fim": "2026-08-09",
      "produtos": 21,
      "ativas": 4,
      "usaram": 6,
      "cadastros": 7,
      "novos": 2
    },
    {
      "inicio": "2026-08-10",
      "fim": "2026-08-16",
      "produtos": 123,
      "ativas": 3,
      "usaram": 5,
      "cadastros": 9,
      "novos": 2
    },
    {
      "inicio": "2026-08-17",
      "fim": "2026-08-23",
      "produtos": 64,
      "ativas": 4,
      "usaram": 6,
      "cadastros": 9,
      "novos": 0
    },
    {
      "inicio": "2026-08-24",
      "fim": "2026-08-30",
      "produtos": 80,
      "ativas": 4,
      "usaram": 5,
      "cadastros": 9,
      "novos": 0
    },
    {
      "inicio": "2026-08-31",
      "fim": "2026-09-06",
      "produtos": 47,
      "ativas": 5,
      "usaram": 7,
      "cadastros": 10,
      "novos": 1
    },
    {
      "inicio": "2026-09-07",
      "fim": "2026-09-13",
      "produtos": 24,
      "ativas": 2,
      "usaram": 3,
      "cadastros": 10,
      "novos": 0
    }
  ],
  "apps": {
    "auto": {
      "id": "auto",
      "nome": "Piloto automático",
      "prefixo": "app:auto:",
      "kpis": {
        "liberadas": 19,
        "ativas": 3,
        "usando": 7,
        "nunca_usaram": 12,
        "paradas": 2,
        "com_conta": 11,
        "contas": 10,
        "produtos_total": 294,
        "produtos_7d": 57,
        "descricoes_total": 377,
        "total_estimado": true,
        "produtos_atribuidos": 5
      },
      "marcas": [
        {
          "slug": "nicoboco",
          "nome": "Nicoboco",
          "arquetipo": "explorador",
          "tem_conta": true,
          "email": "nicoboco.shop@nicoboco.com.br",
          "produtos": 174,
          "estimado": false,
          "produtos_7d": 42,
          "ativa": true,
          "acessos": 53,
          "buscas": 282,
          "descricoes": 222,
          "envios": 226,
          "primeiro": "2026-08-11T18:28:02.542Z",
          "ultimo": "2026-09-07T16:09:00.194Z",
          "dias": 0,
          "produtos_medidos": 174,
          "atribuido": 0
        },
        {
          "slug": "opera-kids",
          "nome": "Ópera Kids",
          "arquetipo": "inocente",
          "tem_conta": true,
          "email": "contato@operakids.com.br",
          "produtos": 81,
          "estimado": true,
          "produtos_7d": 1,
          "ativa": false,
          "acessos": 13,
          "buscas": 77,
          "descricoes": 106,
          "envios": 103,
          "primeiro": "2026-08-18T13:22:59.954Z",
          "ultimo": "2026-09-02T17:11:58.593Z",
          "dias": 5,
          "produtos_medidos": 76,
          "atribuido": 5
        },
        {
          "slug": "petit",
          "nome": "Petit",
          "arquetipo": "inocente",
          "tem_conta": true,
          "email": "anderson@mundotaci.com.br",
          "produtos": 14,
          "estimado": false,
          "produtos_7d": 0,
          "ativa": false,
          "acessos": 0,
          "buscas": 0,
          "descricoes": 14,
          "envios": 14,
          "primeiro": "2026-08-27T10:08:32.689Z",
          "ultimo": "2026-08-31T19:02:37.837Z",
          "dias": 7,
          "produtos_medidos": 14,
          "atribuido": 0
        },
        {
          "slug": "monnika-marikinha",
          "nome": "Monnika Marikinha",
          "arquetipo": "amante",
          "tem_conta": true,
          "email": "monnikamarikinhaloja@gmail.com",
          "produtos": 10,
          "estimado": false,
          "produtos_7d": 6,
          "ativa": true,
          "acessos": 0,
          "buscas": 0,
          "descricoes": 10,
          "envios": 10,
          "primeiro": "2026-08-21T01:34:17.651Z",
          "ultimo": "2026-09-03T17:32:55.872Z",
          "dias": 4,
          "produtos_medidos": 10,
          "atribuido": 0
        },
        {
          "slug": "kauly",
          "nome": "Kauly",
          "arquetipo": "governante",
          "tem_conta": true,
          "email": "marketing@kauly.com.br",
          "produtos": 8,
          "estimado": false,
          "produtos_7d": 8,
          "ativa": true,
          "acessos": 2,
          "buscas": 7,
          "descricoes": 11,
          "envios": 9,
          "primeiro": "2026-09-02T19:08:41.700Z",
          "ultimo": "2026-09-08T15:00:22.895Z",
          "dias": 0,
          "produtos_medidos": 8,
          "atribuido": 0
        },
        {
          "slug": "amiska",
          "nome": "Amiska",
          "arquetipo": "sabio",
          "tem_conta": true,
          "email": "missmilliebr@gmail.com",
          "produtos": 4,
          "estimado": false,
          "produtos_7d": 0,
          "ativa": false,
          "acessos": 0,
          "buscas": 0,
          "descricoes": 4,
          "envios": 4,
          "primeiro": "2026-08-21T01:32:04.730Z",
          "ultimo": "2026-08-21T01:32:24.963Z",
          "dias": 18,
          "produtos_medidos": 4,
          "atribuido": 0
        },
        {
          "slug": "andressa-vesti",
          "nome": "Andressa Vesti",
          "arquetipo": "rebelde",
          "tem_conta": true,
          "email": "andressavazpinto@gmail.commx",
          "produtos": 3,
          "estimado": false,
          "produtos_7d": 0,
          "ativa": false,
          "acessos": 16,
          "buscas": 46,
          "descricoes": 10,
          "envios": 4,
          "primeiro": "2026-08-13T17:14:37.157Z",
          "ultimo": "2026-08-20T11:06:21.271Z",
          "dias": 19,
          "produtos_medidos": 3,
          "atribuido": 0
        },
        {
          "slug": "anne-blanc",
          "nome": "Anne Blanc",
          "arquetipo": "",
          "tem_conta": false,
          "email": "",
          "produtos": 0,
          "estimado": false,
          "produtos_7d": 0,
          "ativa": false,
          "acessos": 0,
          "buscas": 0,
          "descricoes": 0,
          "envios": 0,
          "primeiro": "",
          "ultimo": "",
          "dias": null,
          "produtos_medidos": 0,
          "atribuido": 0
        },
        {
          "slug": "demissy",
          "nome": "DeMissy",
          "arquetipo": "",
          "tem_conta": true,
          "email": "comercial.danque@gmail.com",
          "produtos": 0,
          "estimado": false,
          "produtos_7d": 0,
          "ativa": false,
          "acessos": 0,
          "buscas": 0,
          "descricoes": 0,
          "envios": 0,
          "primeiro": "",
          "ultimo": "",
          "dias": null,
          "produtos_medidos": 0,
          "atribuido": 0
        },
        {
          "slug": "gitaa",
          "nome": "Gitaa",
          "arquetipo": "",
          "tem_conta": false,
          "email": "",
          "produtos": 0,
          "estimado": false,
          "produtos_7d": 0,
          "ativa": false,
          "acessos": 0,
          "buscas": 0,
          "descricoes": 0,
          "envios": 0,
          "primeiro": "",
          "ultimo": "",
          "dias": null,
          "produtos_medidos": 0,
          "atribuido": 0
        },
        {
          "slug": "kauly-varejo",
          "nome": "Kauly varejo",
          "arquetipo": "",
          "tem_conta": false,
          "email": "",
          "produtos": 0,
          "estimado": false,
          "produtos_7d": 0,
          "ativa": false,
          "acessos": 0,
          "buscas": 0,
          "descricoes": 0,
          "envios": 0,
          "primeiro": "",
          "ultimo": "",
          "dias": null,
          "produtos_medidos": 0,
          "atribuido": 0
        },
        {
          "slug": "luciana-pais",
          "nome": "Luciana Pais",
          "arquetipo": "governante",
          "tem_conta": false,
          "email": "",
          "produtos": 0,
          "estimado": false,
          "produtos_7d": 0,
          "ativa": false,
          "acessos": 0,
          "buscas": 0,
          "descricoes": 0,
          "envios": 0,
          "primeiro": "",
          "ultimo": "",
          "dias": null,
          "produtos_medidos": 0,
          "atribuido": 0
        },
        {
          "slug": "murano",
          "nome": "Murano",
          "arquetipo": "",
          "tem_conta": false,
          "email": "",
          "produtos": 0,
          "estimado": false,
          "produtos_7d": 0,
          "ativa": false,
          "acessos": 0,
          "buscas": 0,
          "descricoes": 0,
          "envios": 0,
          "primeiro": "",
          "ultimo": "",
          "dias": null,
          "produtos_medidos": 0,
          "atribuido": 0
        },
        {
          "slug": "murano-filial",
          "nome": "Murano filial",
          "arquetipo": "",
          "tem_conta": false,
          "email": "",
          "produtos": 0,
          "estimado": false,
          "produtos_7d": 0,
          "ativa": false,
          "acessos": 0,
          "buscas": 0,
          "descricoes": 0,
          "envios": 0,
          "primeiro": "",
          "ultimo": "",
          "dias": null,
          "produtos_medidos": 0,
          "atribuido": 0
        },
        {
          "slug": "optimist-feirinha",
          "nome": "Optimist Feirinha",
          "arquetipo": "",
          "tem_conta": true,
          "email": "ecommerce@optimistjeans.com.br",
          "produtos": 0,
          "estimado": false,
          "produtos_7d": 0,
          "ativa": false,
          "acessos": 0,
          "buscas": 0,
          "descricoes": 0,
          "envios": 0,
          "primeiro": "",
          "ultimo": "",
          "dias": null,
          "produtos_medidos": 0,
          "atribuido": 0
        },
        {
          "slug": "optimist-jeans",
          "nome": "Optimist Jeans",
          "arquetipo": "governante",
          "tem_conta": true,
          "email": "ecommerce@optimistjeans.com.br",
          "produtos": 0,
          "estimado": false,
          "produtos_7d": 0,
          "ativa": false,
          "acessos": 0,
          "buscas": 0,
          "descricoes": 0,
          "envios": 0,
          "primeiro": "",
          "ultimo": "",
          "dias": null,
          "produtos_medidos": 0,
          "atribuido": 0
        },
        {
          "slug": "stefani",
          "nome": "Stefani",
          "arquetipo": "",
          "tem_conta": false,
          "email": "",
          "produtos": 0,
          "estimado": false,
          "produtos_7d": 0,
          "ativa": false,
          "acessos": 0,
          "buscas": 0,
          "descricoes": 0,
          "envios": 0,
          "primeiro": "",
          "ultimo": "",
          "dias": null,
          "produtos_medidos": 0,
          "atribuido": 0
        },
        {
          "slug": "trimix",
          "nome": "Trimix",
          "arquetipo": "heroi",
          "tem_conta": true,
          "email": "salomon@trimix.com.br",
          "produtos": 0,
          "estimado": false,
          "produtos_7d": 0,
          "ativa": false,
          "acessos": 0,
          "buscas": 0,
          "descricoes": 0,
          "envios": 0,
          "primeiro": "",
          "ultimo": "",
          "dias": null,
          "produtos_medidos": 0,
          "atribuido": 0
        },
        {
          "slug": "ttng",
          "nome": "TTNG",
          "arquetipo": "",
          "tem_conta": false,
          "email": "",
          "produtos": 0,
          "estimado": false,
          "produtos_7d": 0,
          "ativa": false,
          "acessos": 0,
          "buscas": 0,
          "descricoes": 0,
          "envios": 0,
          "primeiro": "",
          "ultimo": "",
          "dias": null,
          "produtos_medidos": 0,
          "atribuido": 0
        }
      ],
      "semanas": [
        {
          "inicio": "2026-06-22",
          "fim": "2026-06-28",
          "produtos": 0,
          "ativas": 0,
          "usaram": 0,
          "cadastros": 0,
          "novos": 0,
          "produtos_medidos": 0,
          "atribuido": 0
        },
        {
          "inicio": "2026-06-29",
          "fim": "2026-07-05",
          "produtos": 0,
          "ativas": 0,
          "usaram": 0,
          "cadastros": 0,
          "novos": 0,
          "produtos_medidos": 0,
          "atribuido": 0
        },
        {
          "inicio": "2026-07-06",
          "fim": "2026-07-12",
          "produtos": 0,
          "ativas": 0,
          "usaram": 0,
          "cadastros": 0,
          "novos": 0,
          "produtos_medidos": 0,
          "atribuido": 0
        },
        {
          "inicio": "2026-07-13",
          "fim": "2026-07-19",
          "produtos": 0,
          "ativas": 0,
          "usaram": 0,
          "cadastros": 3,
          "novos": 3,
          "produtos_medidos": 0,
          "atribuido": 0
        },
        {
          "inicio": "2026-07-20",
          "fim": "2026-07-26",
          "produtos": 0,
          "ativas": 0,
          "usaram": 0,
          "cadastros": 5,
          "novos": 2,
          "produtos_medidos": 0,
          "atribuido": 0
        },
        {
          "inicio": "2026-07-27",
          "fim": "2026-08-02",
          "produtos": 0,
          "ativas": 0,
          "usaram": 0,
          "cadastros": 5,
          "novos": 0,
          "produtos_medidos": 0,
          "atribuido": 0
        },
        {
          "inicio": "2026-08-03",
          "fim": "2026-08-09",
          "produtos": 0,
          "ativas": 0,
          "usaram": 0,
          "cadastros": 7,
          "novos": 2,
          "produtos_medidos": 0,
          "atribuido": 0
        },
        {
          "inicio": "2026-08-10",
          "fim": "2026-08-16",
          "produtos": 105,
          "ativas": 2,
          "usaram": 2,
          "cadastros": 9,
          "novos": 2,
          "produtos_medidos": 105,
          "atribuido": 0
        },
        {
          "inicio": "2026-08-17",
          "fim": "2026-08-23",
          "produtos": 58,
          "ativas": 4,
          "usaram": 5,
          "cadastros": 9,
          "novos": 0,
          "produtos_medidos": 56,
          "atribuido": 2
        },
        {
          "inicio": "2026-08-24",
          "fim": "2026-08-30",
          "produtos": 73,
          "ativas": 3,
          "usaram": 3,
          "cadastros": 9,
          "novos": 0,
          "produtos_medidos": 73,
          "atribuido": 0
        },
        {
          "inicio": "2026-08-31",
          "fim": "2026-09-06",
          "produtos": 39,
          "ativas": 4,
          "usaram": 5,
          "cadastros": 10,
          "novos": 1,
          "produtos_medidos": 39,
          "atribuido": 0
        },
        {
          "inicio": "2026-09-07",
          "fim": "2026-09-13",
          "produtos": 22,
          "ativas": 1,
          "usaram": 2,
          "cadastros": 10,
          "novos": 0,
          "produtos_medidos": 22,
          "atribuido": 0
        }
      ]
    },
    "manual": {
      "id": "manual",
      "nome": "Manual",
      "prefixo": "app:manual:",
      "kpis": {
        "liberadas": 19,
        "ativas": 1,
        "usando": 10,
        "nunca_usaram": 9,
        "paradas": 1,
        "com_conta": 11,
        "contas": 10,
        "produtos_total": 209,
        "produtos_7d": 10,
        "descricoes_total": 76,
        "total_estimado": true,
        "produtos_atribuidos": 180
      },
      "marcas": [
        {
          "slug": "nicoboco",
          "nome": "Nicoboco",
          "arquetipo": "explorador",
          "tem_conta": true,
          "email": "nicoboco.shop@nicoboco.com.br",
          "produtos": 82,
          "estimado": true,
          "produtos_7d": 0,
          "ativa": false,
          "acessos": 0,
          "buscas": 0,
          "descricoes": 0,
          "envios": 0,
          "primeiro": "",
          "ultimo": "",
          "dias": null,
          "produtos_medidos": 0,
          "atribuido": 82
        },
        {
          "slug": "amiska",
          "nome": "Amiska",
          "arquetipo": "sabio",
          "tem_conta": true,
          "email": "missmilliebr@gmail.com",
          "produtos": 79,
          "estimado": true,
          "produtos_7d": 10,
          "ativa": true,
          "acessos": 6,
          "buscas": 28,
          "descricoes": 39,
          "envios": 29,
          "primeiro": "2026-08-17T12:54:41.838Z",
          "ultimo": "2026-09-08T13:36:15.255Z",
          "dias": 0,
          "produtos_medidos": 27,
          "atribuido": 52
        },
        {
          "slug": "petit",
          "nome": "Petit",
          "arquetipo": "inocente",
          "tem_conta": true,
          "email": "anderson@mundotaci.com.br",
          "produtos": 30,
          "estimado": true,
          "produtos_7d": 0,
          "ativa": false,
          "acessos": 0,
          "buscas": 0,
          "descricoes": 0,
          "envios": 0,
          "primeiro": "",
          "ultimo": "",
          "dias": null,
          "produtos_medidos": 0,
          "atribuido": 30
        },
        {
          "slug": "andressa-vesti",
          "nome": "Andressa Vesti",
          "arquetipo": "rebelde",
          "tem_conta": true,
          "email": "andressavazpinto@gmail.commx",
          "produtos": 8,
          "estimado": true,
          "produtos_7d": 0,
          "ativa": false,
          "acessos": 2,
          "buscas": 1,
          "descricoes": 0,
          "envios": 0,
          "primeiro": "2026-08-14T12:06:46.387Z",
          "ultimo": "2026-08-20T02:30:36.116Z",
          "dias": 19,
          "produtos_medidos": 0,
          "atribuido": 8
        },
        {
          "slug": "optimist-jeans",
          "nome": "Optimist Jeans",
          "arquetipo": "governante",
          "tem_conta": true,
          "email": "ecommerce@optimistjeans.com.br",
          "produtos": 3,
          "estimado": true,
          "produtos_7d": 0,
          "ativa": false,
          "acessos": 0,
          "buscas": 0,
          "descricoes": 0,
          "envios": 0,
          "primeiro": "",
          "ultimo": "",
          "dias": null,
          "produtos_medidos": 0,
          "atribuido": 3
        },
        {
          "slug": "monnika-marikinha",
          "nome": "Monnika Marikinha",
          "arquetipo": "amante",
          "tem_conta": true,
          "email": "monnikamarikinhaloja@gmail.com",
          "produtos": 2,
          "estimado": true,
          "produtos_7d": 0,
          "ativa": false,
          "acessos": 0,
          "buscas": 0,
          "descricoes": 0,
          "envios": 0,
          "primeiro": "",
          "ultimo": "",
          "dias": null,
          "produtos_medidos": 0,
          "atribuido": 2
        },
        {
          "slug": "opera-kids",
          "nome": "Ópera Kids",
          "arquetipo": "inocente",
          "tem_conta": true,
          "email": "contato@operakids.com.br",
          "produtos": 2,
          "estimado": false,
          "produtos_7d": 0,
          "ativa": false,
          "acessos": 17,
          "buscas": 10,
          "descricoes": 10,
          "envios": 3,
          "primeiro": "2026-08-12T12:05:03.861Z",
          "ultimo": "2026-08-31T17:32:53.474Z",
          "dias": 7,
          "produtos_medidos": 2,
          "atribuido": 0
        },
        {
          "slug": "optimist-feirinha",
          "nome": "Optimist Feirinha",
          "arquetipo": "",
          "tem_conta": true,
          "email": "ecommerce@optimistjeans.com.br",
          "produtos": 2,
          "estimado": true,
          "produtos_7d": 0,
          "ativa": false,
          "acessos": 0,
          "buscas": 0,
          "descricoes": 0,
          "envios": 0,
          "primeiro": "",
          "ultimo": "",
          "dias": null,
          "produtos_medidos": 0,
          "atribuido": 2
        },
        {
          "slug": "kauly",
          "nome": "Kauly",
          "arquetipo": "governante",
          "tem_conta": true,
          "email": "marketing@kauly.com.br",
          "produtos": 1,
          "estimado": true,
          "produtos_7d": 0,
          "ativa": false,
          "acessos": 0,
          "buscas": 0,
          "descricoes": 0,
          "envios": 0,
          "primeiro": "",
          "ultimo": "",
          "dias": null,
          "produtos_medidos": 0,
          "atribuido": 1
        },
        {
          "slug": "anne-blanc",
          "nome": "Anne Blanc",
          "arquetipo": "",
          "tem_conta": false,
          "email": "",
          "produtos": 0,
          "estimado": false,
          "produtos_7d": 0,
          "ativa": false,
          "acessos": 0,
          "buscas": 0,
          "descricoes": 0,
          "envios": 0,
          "primeiro": "",
          "ultimo": "",
          "dias": null,
          "produtos_medidos": 0,
          "atribuido": 0
        },
        {
          "slug": "demissy",
          "nome": "DeMissy",
          "arquetipo": "",
          "tem_conta": true,
          "email": "comercial.danque@gmail.com",
          "produtos": 0,
          "estimado": false,
          "produtos_7d": 0,
          "ativa": false,
          "acessos": 0,
          "buscas": 0,
          "descricoes": 0,
          "envios": 0,
          "primeiro": "",
          "ultimo": "",
          "dias": null,
          "produtos_medidos": 0,
          "atribuido": 0
        },
        {
          "slug": "gitaa",
          "nome": "Gitaa",
          "arquetipo": "",
          "tem_conta": false,
          "email": "",
          "produtos": 0,
          "estimado": false,
          "produtos_7d": 0,
          "ativa": false,
          "acessos": 0,
          "buscas": 0,
          "descricoes": 0,
          "envios": 0,
          "primeiro": "",
          "ultimo": "",
          "dias": null,
          "produtos_medidos": 0,
          "atribuido": 0
        },
        {
          "slug": "kauly-varejo",
          "nome": "Kauly varejo",
          "arquetipo": "",
          "tem_conta": false,
          "email": "",
          "produtos": 0,
          "estimado": false,
          "produtos_7d": 0,
          "ativa": false,
          "acessos": 0,
          "buscas": 0,
          "descricoes": 0,
          "envios": 0,
          "primeiro": "",
          "ultimo": "",
          "dias": null,
          "produtos_medidos": 0,
          "atribuido": 0
        },
        {
          "slug": "luciana-pais",
          "nome": "Luciana Pais",
          "arquetipo": "governante",
          "tem_conta": false,
          "email": "",
          "produtos": 0,
          "estimado": false,
          "produtos_7d": 0,
          "ativa": false,
          "acessos": 0,
          "buscas": 0,
          "descricoes": 0,
          "envios": 0,
          "primeiro": "",
          "ultimo": "",
          "dias": null,
          "produtos_medidos": 0,
          "atribuido": 0
        },
        {
          "slug": "murano",
          "nome": "Murano",
          "arquetipo": "",
          "tem_conta": false,
          "email": "",
          "produtos": 0,
          "estimado": false,
          "produtos_7d": 0,
          "ativa": false,
          "acessos": 0,
          "buscas": 0,
          "descricoes": 0,
          "envios": 0,
          "primeiro": "",
          "ultimo": "",
          "dias": null,
          "produtos_medidos": 0,
          "atribuido": 0
        },
        {
          "slug": "murano-filial",
          "nome": "Murano filial",
          "arquetipo": "",
          "tem_conta": false,
          "email": "",
          "produtos": 0,
          "estimado": false,
          "produtos_7d": 0,
          "ativa": false,
          "acessos": 0,
          "buscas": 0,
          "descricoes": 0,
          "envios": 0,
          "primeiro": "",
          "ultimo": "",
          "dias": null,
          "produtos_medidos": 0,
          "atribuido": 0
        },
        {
          "slug": "stefani",
          "nome": "Stefani",
          "arquetipo": "",
          "tem_conta": false,
          "email": "",
          "produtos": 0,
          "estimado": false,
          "produtos_7d": 0,
          "ativa": false,
          "acessos": 0,
          "buscas": 0,
          "descricoes": 0,
          "envios": 0,
          "primeiro": "",
          "ultimo": "",
          "dias": null,
          "produtos_medidos": 0,
          "atribuido": 0
        },
        {
          "slug": "trimix",
          "nome": "Trimix",
          "arquetipo": "heroi",
          "tem_conta": true,
          "email": "salomon@trimix.com.br",
          "produtos": 0,
          "estimado": false,
          "produtos_7d": 0,
          "ativa": false,
          "acessos": 7,
          "buscas": 28,
          "descricoes": 27,
          "envios": 0,
          "primeiro": "2026-08-14T11:49:43.332Z",
          "ultimo": "2026-09-01T13:07:03.363Z",
          "dias": 7,
          "produtos_medidos": 0,
          "atribuido": 0
        },
        {
          "slug": "ttng",
          "nome": "TTNG",
          "arquetipo": "",
          "tem_conta": false,
          "email": "",
          "produtos": 0,
          "estimado": false,
          "produtos_7d": 0,
          "ativa": false,
          "acessos": 0,
          "buscas": 0,
          "descricoes": 0,
          "envios": 0,
          "primeiro": "",
          "ultimo": "",
          "dias": null,
          "produtos_medidos": 0,
          "atribuido": 0
        }
      ],
      "semanas": [
        {
          "inicio": "2026-06-22",
          "fim": "2026-06-28",
          "produtos": 0,
          "ativas": 0,
          "usaram": 0,
          "cadastros": 0,
          "novos": 0,
          "produtos_medidos": 0,
          "atribuido": 0
        },
        {
          "inicio": "2026-06-29",
          "fim": "2026-07-05",
          "produtos": 0,
          "ativas": 0,
          "usaram": 0,
          "cadastros": 0,
          "novos": 0,
          "produtos_medidos": 0,
          "atribuido": 0
        },
        {
          "inicio": "2026-07-06",
          "fim": "2026-07-12",
          "produtos": 0,
          "ativas": 0,
          "usaram": 0,
          "cadastros": 0,
          "novos": 0,
          "produtos_medidos": 0,
          "atribuido": 0
        },
        {
          "inicio": "2026-07-13",
          "fim": "2026-07-19",
          "produtos": 0,
          "ativas": 0,
          "usaram": 0,
          "cadastros": 3,
          "novos": 3,
          "produtos_medidos": 0,
          "atribuido": 0
        },
        {
          "inicio": "2026-07-20",
          "fim": "2026-07-26",
          "produtos": 0,
          "ativas": 0,
          "usaram": 0,
          "cadastros": 5,
          "novos": 2,
          "produtos_medidos": 0,
          "atribuido": 0
        },
        {
          "inicio": "2026-07-27",
          "fim": "2026-08-02",
          "produtos": 13,
          "ativas": 0,
          "usaram": 0,
          "cadastros": 5,
          "novos": 0,
          "produtos_medidos": 0,
          "atribuido": 13
        },
        {
          "inicio": "2026-08-03",
          "fim": "2026-08-09",
          "produtos": 21,
          "ativas": 0,
          "usaram": 0,
          "cadastros": 7,
          "novos": 2,
          "produtos_medidos": 0,
          "atribuido": 21
        },
        {
          "inicio": "2026-08-10",
          "fim": "2026-08-16",
          "produtos": 99,
          "ativas": 0,
          "usaram": 3,
          "cadastros": 9,
          "novos": 2,
          "produtos_medidos": 0,
          "atribuido": 99
        },
        {
          "inicio": "2026-08-17",
          "fim": "2026-08-23",
          "produtos": 14,
          "ativas": 2,
          "usaram": 4,
          "cadastros": 9,
          "novos": 0,
          "produtos_medidos": 12,
          "atribuido": 2
        },
        {
          "inicio": "2026-08-24",
          "fim": "2026-08-30",
          "produtos": 9,
          "ativas": 1,
          "usaram": 2,
          "cadastros": 9,
          "novos": 0,
          "produtos_medidos": 7,
          "atribuido": 2
        },
        {
          "inicio": "2026-08-31",
          "fim": "2026-09-06",
          "produtos": 12,
          "ativas": 1,
          "usaram": 3,
          "cadastros": 10,
          "novos": 1,
          "produtos_medidos": 8,
          "atribuido": 4
        },
        {
          "inicio": "2026-09-07",
          "fim": "2026-09-13",
          "produtos": 3,
          "ativas": 1,
          "usaram": 1,
          "cadastros": 10,
          "novos": 0,
          "produtos_medidos": 2,
          "atribuido": 1
        }
      ]
    }
  }
};
