window.DADOS = {
  "gerado_em": "2026-10-09T17:45:56.516Z",
  "hoje": "2026-10-09",
  "medindo_desde": "2026-07-24T17:20:05.000Z",
  "apps_desde": "2026-08-11T18:28:02.542Z",
  "auto_publica_desde": "2026-08-10",
  "criterio": {
    "produtos_semana": 2,
    "dias_parada": 7,
    "janela_dias": 7,
    "semanas": 12
  },
  "kpis": {
    "liberadas": 19,
    "ativas": 4,
    "usando": 11,
    "nunca_usaram": 8,
    "paradas": 6,
    "com_conta": 11,
    "contas": 10,
    "produtos_total": 2347,
    "produtos_7d": 50,
    "descricoes_total": 2679,
    "total_estimado": true
  },
  "marcas": [
    {
      "slug": "luciana-pais",
      "nome": "Luciana Pais",
      "arquetipo": "governante",
      "tem_conta": false,
      "email": "",
      "produtos": 774,
      "estimado": false,
      "produtos_7d": 0,
      "ativa": false,
      "acessos": 0,
      "buscas": 0,
      "descricoes": 780,
      "envios": 780,
      "primeiro": "2026-09-24T17:58:46.470Z",
      "ultimo": "2026-09-24T20:17:17.985Z",
      "dias": 14
    },
    {
      "slug": "kauly",
      "nome": "Kauly",
      "arquetipo": "governante",
      "tem_conta": true,
      "email": "marketing@kauly.com.br",
      "produtos": 749,
      "estimado": false,
      "produtos_7d": 0,
      "ativa": false,
      "acessos": 2,
      "buscas": 7,
      "descricoes": 763,
      "envios": 761,
      "primeiro": "2026-09-02T19:08:41.700Z",
      "ultimo": "2026-09-24T17:58:40.316Z",
      "dias": 14
    },
    {
      "slug": "petit",
      "nome": "Petit",
      "arquetipo": "inocente",
      "tem_conta": true,
      "email": "anderson@mundotaci.com.br",
      "produtos": 251,
      "estimado": false,
      "produtos_7d": 0,
      "ativa": false,
      "acessos": 5,
      "buscas": 283,
      "descricoes": 289,
      "envios": 294,
      "primeiro": "2026-08-27T10:08:32.689Z",
      "ultimo": "2026-09-16T16:01:07.318Z",
      "dias": 23
    },
    {
      "slug": "nicoboco",
      "nome": "Nicoboco",
      "arquetipo": "explorador",
      "tem_conta": true,
      "email": "nicoboco.shop@nicoboco.com.br",
      "produtos": 230,
      "estimado": false,
      "produtos_7d": 17,
      "ativa": true,
      "acessos": 74,
      "buscas": 346,
      "descricoes": 343,
      "envios": 369,
      "primeiro": "2026-08-10T19:02:35.392Z",
      "ultimo": "2026-10-08T11:29:19.922Z",
      "dias": 1
    },
    {
      "slug": "opera-kids",
      "nome": "Ópera Kids",
      "arquetipo": "inocente",
      "tem_conta": true,
      "email": "contato@operakids.com.br",
      "produtos": 173,
      "estimado": false,
      "produtos_7d": 16,
      "ativa": true,
      "acessos": 92,
      "buscas": 242,
      "descricoes": 241,
      "envios": 210,
      "primeiro": "2026-07-28T11:47:18.529Z",
      "ultimo": "2026-10-08T21:23:42.517Z",
      "dias": 0
    },
    {
      "slug": "amiska",
      "nome": "Amiska",
      "arquetipo": "sabio",
      "tem_conta": true,
      "email": "missmilliebr@gmail.com",
      "produtos": 122,
      "estimado": true,
      "produtos_7d": 14,
      "ativa": true,
      "acessos": 16,
      "buscas": 95,
      "descricoes": 119,
      "envios": 115,
      "primeiro": "2026-07-28T18:41:18.639Z",
      "ultimo": "2026-10-08T13:05:36.930Z",
      "dias": 1
    },
    {
      "slug": "monnika-marikinha",
      "nome": "Monnika Marikinha",
      "arquetipo": "amante",
      "tem_conta": true,
      "email": "monnikamarikinhaloja@gmail.com",
      "produtos": 20,
      "estimado": false,
      "produtos_7d": 3,
      "ativa": true,
      "acessos": 2,
      "buscas": 1,
      "descricoes": 20,
      "envios": 20,
      "primeiro": "2026-08-06T14:16:43.085Z",
      "ultimo": "2026-10-09T09:19:21.110Z",
      "dias": 0
    },
    {
      "slug": "trimix",
      "nome": "Trimix",
      "arquetipo": "heroi",
      "tem_conta": true,
      "email": "salomon@trimix.com.br",
      "produtos": 13,
      "estimado": false,
      "produtos_7d": 0,
      "ativa": false,
      "acessos": 30,
      "buscas": 88,
      "descricoes": 97,
      "envios": 13,
      "primeiro": "2026-08-04T14:28:52.117Z",
      "ultimo": "2026-10-09T16:19:18.109Z",
      "dias": 0
    },
    {
      "slug": "andressa-vesti",
      "nome": "Andressa Vesti",
      "arquetipo": "rebelde",
      "tem_conta": true,
      "email": "andressavazpinto@gmail.commx",
      "produtos": 10,
      "estimado": false,
      "produtos_7d": 0,
      "ativa": false,
      "acessos": 36,
      "buscas": 73,
      "descricoes": 23,
      "envios": 13,
      "primeiro": "2026-08-10T16:01:03.796Z",
      "ultimo": "2026-09-28T16:09:38.397Z",
      "dias": 11
    },
    {
      "slug": "optimist-jeans",
      "nome": "Optimist Jeans",
      "arquetipo": "governante",
      "tem_conta": true,
      "email": "ecommerce@optimistjeans.com.br",
      "produtos": 3,
      "estimado": false,
      "produtos_7d": 0,
      "ativa": false,
      "acessos": 3,
      "buscas": 3,
      "descricoes": 4,
      "envios": 5,
      "primeiro": "2026-08-07T13:23:05.929Z",
      "ultimo": "2026-08-07T14:55:31.596Z",
      "dias": 63
    },
    {
      "slug": "optimist-feirinha",
      "nome": "Optimist Feirinha",
      "arquetipo": "",
      "tem_conta": true,
      "email": "ecommerce@optimistjeans.com.br",
      "produtos": 2,
      "estimado": false,
      "produtos_7d": 0,
      "ativa": false,
      "acessos": 0,
      "buscas": 1,
      "descricoes": 0,
      "envios": 2,
      "primeiro": "2026-08-07T13:33:14.591Z",
      "ultimo": "2026-08-07T14:33:01.598Z",
      "dias": 63
    },
    {
      "slug": "anne-blanc",
      "nome": "Anne Blanc",
      "arquetipo": "",
      "tem_conta": false,
      "email": "",
      "produtos": 0,
      "estimado": false,
      "produtos_7d": 0,
      "ativa": false,
      "acessos": 0,
      "buscas": 0,
      "descricoes": 0,
      "envios": 0,
      "primeiro": "",
      "ultimo": "",
      "dias": null
    },
    {
      "slug": "demissy",
      "nome": "DeMissy",
      "arquetipo": "",
      "tem_conta": true,
      "email": "comercial.danque@gmail.com",
      "produtos": 0,
      "estimado": false,
      "produtos_7d": 0,
      "ativa": false,
      "acessos": 0,
      "buscas": 0,
      "descricoes": 0,
      "envios": 0,
      "primeiro": "",
      "ultimo": "",
      "dias": null
    },
    {
      "slug": "gitaa",
      "nome": "Gitaa",
      "arquetipo": "",
      "tem_conta": false,
      "email": "",
      "produtos": 0,
      "estimado": false,
      "produtos_7d": 0,
      "ativa": false,
      "acessos": 0,
      "buscas": 0,
      "descricoes": 0,
      "envios": 0,
      "primeiro": "",
      "ultimo": "",
      "dias": null
    },
    {
      "slug": "kauly-varejo",
      "nome": "Kauly varejo",
      "arquetipo": "",
      "tem_conta": false,
      "email": "",
      "produtos": 0,
      "estimado": false,
      "produtos_7d": 0,
      "ativa": false,
      "acessos": 0,
      "buscas": 0,
      "descricoes": 0,
      "envios": 0,
      "primeiro": "",
      "ultimo": "",
      "dias": null
    },
    {
      "slug": "murano",
      "nome": "Murano",
      "arquetipo": "",
      "tem_conta": false,
      "email": "",
      "produtos": 0,
      "estimado": false,
      "produtos_7d": 0,
      "ativa": false,
      "acessos": 0,
      "buscas": 0,
      "descricoes": 0,
      "envios": 0,
      "primeiro": "",
      "ultimo": "",
      "dias": null
    },
    {
      "slug": "murano-filial",
      "nome": "Murano filial",
      "arquetipo": "",
      "tem_conta": false,
      "email": "",
      "produtos": 0,
      "estimado": false,
      "produtos_7d": 0,
      "ativa": false,
      "acessos": 0,
      "buscas": 0,
      "descricoes": 0,
      "envios": 0,
      "primeiro": "",
      "ultimo": "",
      "dias": null
    },
    {
      "slug": "stefani",
      "nome": "Stefani",
      "arquetipo": "",
      "tem_conta": false,
      "email": "",
      "produtos": 0,
      "estimado": false,
      "produtos_7d": 0,
      "ativa": false,
      "acessos": 0,
      "buscas": 0,
      "descricoes": 0,
      "envios": 0,
      "primeiro": "",
      "ultimo": "",
      "dias": null
    },
    {
      "slug": "ttng",
      "nome": "TTNG",
      "arquetipo": "",
      "tem_conta": false,
      "email": "",
      "produtos": 0,
      "estimado": false,
      "produtos_7d": 0,
      "ativa": false,
      "acessos": 0,
      "buscas": 0,
      "descricoes": 0,
      "envios": 0,
      "primeiro": "",
      "ultimo": "",
      "dias": null
    }
  ],
  "semanas": [
    {
      "inicio": "2026-07-20",
      "fim": "2026-07-26",
      "produtos": 0,
      "ativas": 0,
      "usaram": 0,
      "cadastros": 5,
      "novos": 2
    },
    {
      "inicio": "2026-07-27",
      "fim": "2026-08-02",
      "produtos": 13,
      "ativas": 2,
      "usaram": 2,
      "cadastros": 5,
      "novos": 0
    },
    {
      "inicio": "2026-08-03",
      "fim": "2026-08-09",
      "produtos": 21,
      "ativas": 4,
      "usaram": 6,
      "cadastros": 7,
      "novos": 2
    },
    {
      "inicio": "2026-08-10",
      "fim": "2026-08-16",
      "produtos": 123,
      "ativas": 3,
      "usaram": 5,
      "cadastros": 9,
      "novos": 2
    },
    {
      "inicio": "2026-08-17",
      "fim": "2026-08-23",
      "produtos": 64,
      "ativas": 4,
      "usaram": 6,
      "cadastros": 9,
      "novos": 0
    },
    {
      "inicio": "2026-08-24",
      "fim": "2026-08-30",
      "produtos": 80,
      "ativas": 4,
      "usaram": 5,
      "cadastros": 9,
      "novos": 0
    },
    {
      "inicio": "2026-08-31",
      "fim": "2026-09-06",
      "produtos": 47,
      "ativas": 5,
      "usaram": 7,
      "cadastros": 10,
      "novos": 1
    },
    {
      "inicio": "2026-09-07",
      "fim": "2026-09-13",
      "produtos": 304,
      "ativas": 5,
      "usaram": 6,
      "cadastros": 10,
      "novos": 0
    },
    {
      "inicio": "2026-09-14",
      "fim": "2026-09-20",
      "produtos": 38,
      "ativas": 4,
      "usaram": 7,
      "cadastros": 10,
      "novos": 0
    },
    {
      "inicio": "2026-09-21",
      "fim": "2026-09-27",
      "produtos": 1549,
      "ativas": 5,
      "usaram": 7,
      "cadastros": 10,
      "novos": 0
    },
    {
      "inicio": "2026-09-28",
      "fim": "2026-10-04",
      "produtos": 153,
      "ativas": 4,
      "usaram": 5,
      "cadastros": 10,
      "novos": 0
    },
    {
      "inicio": "2026-10-05",
      "fim": "2026-10-11",
      "produtos": 33,
      "ativas": 3,
      "usaram": 5,
      "cadastros": 10,
      "novos": 0
    }
  ],
  "apps": {
    "auto": {
      "id": "auto",
      "nome": "Piloto automático",
      "prefixo": "app:auto:",
      "kpis": {
        "liberadas": 19,
        "ativas": 4,
        "usando": 9,
        "nunca_usaram": 10,
        "paradas": 5,
        "com_conta": 11,
        "contas": 10,
        "produtos_total": 1966,
        "produtos_7d": 32,
        "descricoes_total": 2152,
        "total_estimado": false,
        "produtos_atribuidos": 0
      },
      "marcas": [
        {
          "slug": "luciana-pais",
          "nome": "Luciana Pais",
          "arquetipo": "governante",
          "tem_conta": false,
          "email": "",
          "produtos": 774,
          "estimado": false,
          "produtos_7d": 0,
          "ativa": false,
          "acessos": 0,
          "buscas": 0,
          "descricoes": 780,
          "envios": 780,
          "primeiro": "2026-09-24T17:58:46.470Z",
          "ultimo": "2026-09-24T20:17:17.985Z",
          "dias": 14,
          "produtos_medidos": 774,
          "atribuido": 0
        },
        {
          "slug": "kauly",
          "nome": "Kauly",
          "arquetipo": "governante",
          "tem_conta": true,
          "email": "marketing@kauly.com.br",
          "produtos": 749,
          "estimado": false,
          "produtos_7d": 0,
          "ativa": false,
          "acessos": 2,
          "buscas": 7,
          "descricoes": 763,
          "envios": 761,
          "primeiro": "2026-09-02T19:08:41.700Z",
          "ultimo": "2026-09-24T17:58:40.316Z",
          "dias": 14,
          "produtos_medidos": 749,
          "atribuido": 0
        },
        {
          "slug": "nicoboco",
          "nome": "Nicoboco",
          "arquetipo": "explorador",
          "tem_conta": true,
          "email": "nicoboco.shop@nicoboco.com.br",
          "produtos": 228,
          "estimado": false,
          "produtos_7d": 17,
          "ativa": true,
          "acessos": 65,
          "buscas": 306,
          "descricoes": 340,
          "envios": 344,
          "primeiro": "2026-08-11T18:28:02.542Z",
          "ultimo": "2026-10-08T11:29:19.922Z",
          "dias": 1,
          "produtos_medidos": 228,
          "atribuido": 0
        },
        {
          "slug": "opera-kids",
          "nome": "Ópera Kids",
          "arquetipo": "inocente",
          "tem_conta": true,
          "email": "contato@operakids.com.br",
          "produtos": 137,
          "estimado": false,
          "produtos_7d": 7,
          "ativa": true,
          "acessos": 27,
          "buscas": 149,
          "descricoes": 183,
          "envios": 164,
          "primeiro": "2026-08-18T13:22:59.954Z",
          "ultimo": "2026-10-08T21:21:39.545Z",
          "dias": 0,
          "produtos_medidos": 137,
          "atribuido": 0
        },
        {
          "slug": "petit",
          "nome": "Petit",
          "arquetipo": "inocente",
          "tem_conta": true,
          "email": "anderson@mundotaci.com.br",
          "produtos": 30,
          "estimado": false,
          "produtos_7d": 0,
          "ativa": false,
          "acessos": 0,
          "buscas": 0,
          "descricoes": 30,
          "envios": 30,
          "primeiro": "2026-08-27T10:08:32.689Z",
          "ultimo": "2026-09-16T16:01:07.318Z",
          "dias": 23,
          "produtos_medidos": 30,
          "atribuido": 0
        },
        {
          "slug": "monnika-marikinha",
          "nome": "Monnika Marikinha",
          "arquetipo": "amante",
          "tem_conta": true,
          "email": "monnikamarikinhaloja@gmail.com",
          "produtos": 19,
          "estimado": false,
          "produtos_7d": 3,
          "ativa": true,
          "acessos": 0,
          "buscas": 0,
          "descricoes": 19,
          "envios": 19,
          "primeiro": "2026-08-21T01:34:17.651Z",
          "ultimo": "2026-10-09T09:19:21.110Z",
          "dias": 0,
          "produtos_medidos": 19,
          "atribuido": 0
        },
        {
          "slug": "trimix",
          "nome": "Trimix",
          "arquetipo": "heroi",
          "tem_conta": true,
          "email": "salomon@trimix.com.br",
          "produtos": 13,
          "estimado": false,
          "produtos_7d": 0,
          "ativa": false,
          "acessos": 0,
          "buscas": 0,
          "descricoes": 13,
          "envios": 13,
          "primeiro": "2026-09-28T09:19:48.441Z",
          "ultimo": "2026-09-28T17:45:28.264Z",
          "dias": 10,
          "produtos_medidos": 13,
          "atribuido": 0
        },
        {
          "slug": "amiska",
          "nome": "Amiska",
          "arquetipo": "sabio",
          "tem_conta": true,
          "email": "missmilliebr@gmail.com",
          "produtos": 12,
          "estimado": false,
          "produtos_7d": 5,
          "ativa": true,
          "acessos": 0,
          "buscas": 0,
          "descricoes": 12,
          "envios": 12,
          "primeiro": "2026-08-21T01:32:04.730Z",
          "ultimo": "2026-10-07T09:19:48.421Z",
          "dias": 2,
          "produtos_medidos": 12,
          "atribuido": 0
        },
        {
          "slug": "andressa-vesti",
          "nome": "Andressa Vesti",
          "arquetipo": "rebelde",
          "tem_conta": true,
          "email": "andressavazpinto@gmail.commx",
          "produtos": 4,
          "estimado": false,
          "produtos_7d": 0,
          "ativa": false,
          "acessos": 25,
          "buscas": 59,
          "descricoes": 12,
          "envios": 5,
          "primeiro": "2026-08-13T17:14:37.157Z",
          "ultimo": "2026-09-28T16:09:38.397Z",
          "dias": 11,
          "produtos_medidos": 4,
          "atribuido": 0
        },
        {
          "slug": "anne-blanc",
          "nome": "Anne Blanc",
          "arquetipo": "",
          "tem_conta": false,
          "email": "",
          "produtos": 0,
          "estimado": false,
          "produtos_7d": 0,
          "ativa": false,
          "acessos": 0,
          "buscas": 0,
          "descricoes": 0,
          "envios": 0,
          "primeiro": "",
          "ultimo": "",
          "dias": null,
          "produtos_medidos": 0,
          "atribuido": 0
        },
        {
          "slug": "demissy",
          "nome": "DeMissy",
          "arquetipo": "",
          "tem_conta": true,
          "email": "comercial.danque@gmail.com",
          "produtos": 0,
          "estimado": false,
          "produtos_7d": 0,
          "ativa": false,
          "acessos": 0,
          "buscas": 0,
          "descricoes": 0,
          "envios": 0,
          "primeiro": "",
          "ultimo": "",
          "dias": null,
          "produtos_medidos": 0,
          "atribuido": 0
        },
        {
          "slug": "gitaa",
          "nome": "Gitaa",
          "arquetipo": "",
          "tem_conta": false,
          "email": "",
          "produtos": 0,
          "estimado": false,
          "produtos_7d": 0,
          "ativa": false,
          "acessos": 0,
          "buscas": 0,
          "descricoes": 0,
          "envios": 0,
          "primeiro": "",
          "ultimo": "",
          "dias": null,
          "produtos_medidos": 0,
          "atribuido": 0
        },
        {
          "slug": "kauly-varejo",
          "nome": "Kauly varejo",
          "arquetipo": "",
          "tem_conta": false,
          "email": "",
          "produtos": 0,
          "estimado": false,
          "produtos_7d": 0,
          "ativa": false,
          "acessos": 0,
          "buscas": 0,
          "descricoes": 0,
          "envios": 0,
          "primeiro": "",
          "ultimo": "",
          "dias": null,
          "produtos_medidos": 0,
          "atribuido": 0
        },
        {
          "slug": "murano",
          "nome": "Murano",
          "arquetipo": "",
          "tem_conta": false,
          "email": "",
          "produtos": 0,
          "estimado": false,
          "produtos_7d": 0,
          "ativa": false,
          "acessos": 0,
          "buscas": 0,
          "descricoes": 0,
          "envios": 0,
          "primeiro": "",
          "ultimo": "",
          "dias": null,
          "produtos_medidos": 0,
          "atribuido": 0
        },
        {
          "slug": "murano-filial",
          "nome": "Murano filial",
          "arquetipo": "",
          "tem_conta": false,
          "email": "",
          "produtos": 0,
          "estimado": false,
          "produtos_7d": 0,
          "ativa": false,
          "acessos": 0,
          "buscas": 0,
          "descricoes": 0,
          "envios": 0,
          "primeiro": "",
          "ultimo": "",
          "dias": null,
          "produtos_medidos": 0,
          "atribuido": 0
        },
        {
          "slug": "optimist-feirinha",
          "nome": "Optimist Feirinha",
          "arquetipo": "",
          "tem_conta": true,
          "email": "ecommerce@optimistjeans.com.br",
          "produtos": 0,
          "estimado": false,
          "produtos_7d": 0,
          "ativa": false,
          "acessos": 0,
          "buscas": 0,
          "descricoes": 0,
          "envios": 0,
          "primeiro": "",
          "ultimo": "",
          "dias": null,
          "produtos_medidos": 0,
          "atribuido": 0
        },
        {
          "slug": "optimist-jeans",
          "nome": "Optimist Jeans",
          "arquetipo": "governante",
          "tem_conta": true,
          "email": "ecommerce@optimistjeans.com.br",
          "produtos": 0,
          "estimado": false,
          "produtos_7d": 0,
          "ativa": false,
          "acessos": 0,
          "buscas": 0,
          "descricoes": 0,
          "envios": 0,
          "primeiro": "",
          "ultimo": "",
          "dias": null,
          "produtos_medidos": 0,
          "atribuido": 0
        },
        {
          "slug": "stefani",
          "nome": "Stefani",
          "arquetipo": "",
          "tem_conta": false,
          "email": "",
          "produtos": 0,
          "estimado": false,
          "produtos_7d": 0,
          "ativa": false,
          "acessos": 0,
          "buscas": 0,
          "descricoes": 0,
          "envios": 0,
          "primeiro": "",
          "ultimo": "",
          "dias": null,
          "produtos_medidos": 0,
          "atribuido": 0
        },
        {
          "slug": "ttng",
          "nome": "TTNG",
          "arquetipo": "",
          "tem_conta": false,
          "email": "",
          "produtos": 0,
          "estimado": false,
          "produtos_7d": 0,
          "ativa": false,
          "acessos": 0,
          "buscas": 0,
          "descricoes": 0,
          "envios": 0,
          "primeiro": "",
          "ultimo": "",
          "dias": null,
          "produtos_medidos": 0,
          "atribuido": 0
        }
      ],
      "semanas": [
        {
          "inicio": "2026-07-20",
          "fim": "2026-07-26",
          "produtos": 0,
          "ativas": 0,
          "usaram": 0,
          "cadastros": 5,
          "novos": 2,
          "produtos_medidos": 0,
          "atribuido": 0
        },
        {
          "inicio": "2026-07-27",
          "fim": "2026-08-02",
          "produtos": 0,
          "ativas": 0,
          "usaram": 0,
          "cadastros": 5,
          "novos": 0,
          "produtos_medidos": 0,
          "atribuido": 0
        },
        {
          "inicio": "2026-08-03",
          "fim": "2026-08-09",
          "produtos": 0,
          "ativas": 0,
          "usaram": 0,
          "cadastros": 7,
          "novos": 2,
          "produtos_medidos": 0,
          "atribuido": 0
        },
        {
          "inicio": "2026-08-10",
          "fim": "2026-08-16",
          "produtos": 105,
          "ativas": 2,
          "usaram": 2,
          "cadastros": 9,
          "novos": 2,
          "produtos_medidos": 105,
          "atribuido": 0
        },
        {
          "inicio": "2026-08-17",
          "fim": "2026-08-23",
          "produtos": 56,
          "ativas": 4,
          "usaram": 5,
          "cadastros": 9,
          "novos": 0,
          "produtos_medidos": 56,
          "atribuido": 0
        },
        {
          "inicio": "2026-08-24",
          "fim": "2026-08-30",
          "produtos": 73,
          "ativas": 3,
          "usaram": 3,
          "cadastros": 9,
          "novos": 0,
          "produtos_medidos": 73,
          "atribuido": 0
        },
        {
          "inicio": "2026-08-31",
          "fim": "2026-09-06",
          "produtos": 39,
          "ativas": 4,
          "usaram": 5,
          "cadastros": 10,
          "novos": 1,
          "produtos_medidos": 39,
          "atribuido": 0
        },
        {
          "inicio": "2026-09-07",
          "fim": "2026-09-13",
          "produtos": 69,
          "ativas": 5,
          "usaram": 5,
          "cadastros": 10,
          "novos": 0,
          "produtos_medidos": 69,
          "atribuido": 0
        },
        {
          "inicio": "2026-09-14",
          "fim": "2026-09-20",
          "produtos": 22,
          "ativas": 3,
          "usaram": 5,
          "cadastros": 10,
          "novos": 0,
          "produtos_medidos": 22,
          "atribuido": 0
        },
        {
          "inicio": "2026-09-21",
          "fim": "2026-09-27",
          "produtos": 1540,
          "ativas": 3,
          "usaram": 5,
          "cadastros": 10,
          "novos": 0,
          "produtos_medidos": 1540,
          "atribuido": 0
        },
        {
          "inicio": "2026-09-28",
          "fim": "2026-10-04",
          "produtos": 125,
          "ativas": 3,
          "usaram": 4,
          "cadastros": 10,
          "novos": 0,
          "produtos_medidos": 125,
          "atribuido": 0
        },
        {
          "inicio": "2026-10-05",
          "fim": "2026-10-11",
          "produtos": 15,
          "ativas": 3,
          "usaram": 4,
          "cadastros": 10,
          "novos": 0,
          "produtos_medidos": 15,
          "atribuido": 0
        }
      ]
    },
    "manual": {
      "id": "manual",
      "nome": "Manual",
      "prefixo": "app:manual:",
      "kpis": {
        "liberadas": 19,
        "ativas": 2,
        "usando": 11,
        "nunca_usaram": 8,
        "paradas": 2,
        "com_conta": 11,
        "contas": 10,
        "produtos_total": 1698,
        "produtos_7d": 18,
        "descricoes_total": 437,
        "total_estimado": true,
        "produtos_atribuidos": 1357
      },
      "marcas": [
        {
          "slug": "luciana-pais",
          "nome": "Luciana Pais",
          "arquetipo": "governante",
          "tem_conta": false,
          "email": "",
          "produtos": 575,
          "estimado": true,
          "produtos_7d": 0,
          "ativa": false,
          "acessos": 0,
          "buscas": 0,
          "descricoes": 0,
          "envios": 0,
          "primeiro": "",
          "ultimo": "",
          "dias": null,
          "produtos_medidos": 0,
          "atribuido": 575
        },
        {
          "slug": "kauly",
          "nome": "Kauly",
          "arquetipo": "governante",
          "tem_conta": true,
          "email": "marketing@kauly.com.br",
          "produtos": 550,
          "estimado": true,
          "produtos_7d": 0,
          "ativa": false,
          "acessos": 0,
          "buscas": 0,
          "descricoes": 0,
          "envios": 0,
          "primeiro": "",
          "ultimo": "",
          "dias": null,
          "produtos_medidos": 0,
          "atribuido": 550
        },
        {
          "slug": "petit",
          "nome": "Petit",
          "arquetipo": "inocente",
          "tem_conta": true,
          "email": "anderson@mundotaci.com.br",
          "produtos": 241,
          "estimado": false,
          "produtos_7d": 0,
          "ativa": false,
          "acessos": 5,
          "buscas": 283,
          "descricoes": 259,
          "envios": 264,
          "primeiro": "2026-09-09T17:33:37.235Z",
          "ultimo": "2026-09-14T13:57:08.943Z",
          "dias": 25,
          "produtos_medidos": 241,
          "atribuido": 0
        },
        {
          "slug": "amiska",
          "nome": "Amiska",
          "arquetipo": "sabio",
          "tem_conta": true,
          "email": "missmilliebr@gmail.com",
          "produtos": 111,
          "estimado": true,
          "produtos_7d": 9,
          "ativa": true,
          "acessos": 12,
          "buscas": 68,
          "descricoes": 79,
          "envios": 72,
          "primeiro": "2026-08-17T12:54:41.838Z",
          "ultimo": "2026-10-08T13:05:35.473Z",
          "dias": 1,
          "produtos_medidos": 67,
          "atribuido": 44
        },
        {
          "slug": "opera-kids",
          "nome": "Ópera Kids",
          "arquetipo": "inocente",
          "tem_conta": true,
          "email": "contato@operakids.com.br",
          "produtos": 111,
          "estimado": true,
          "produtos_7d": 9,
          "ativa": true,
          "acessos": 21,
          "buscas": 41,
          "descricoes": 41,
          "envios": 34,
          "primeiro": "2026-08-12T12:05:03.861Z",
          "ultimo": "2026-10-08T21:23:40.979Z",
          "dias": 0,
          "produtos_medidos": 33,
          "atribuido": 78
        },
        {
          "slug": "nicoboco",
          "nome": "Nicoboco",
          "arquetipo": "explorador",
          "tem_conta": true,
          "email": "nicoboco.shop@nicoboco.com.br",
          "produtos": 94,
          "estimado": true,
          "produtos_7d": 0,
          "ativa": false,
          "acessos": 0,
          "buscas": 0,
          "descricoes": 0,
          "envios": 0,
          "primeiro": "",
          "ultimo": "",
          "dias": null,
          "produtos_medidos": 0,
          "atribuido": 94
        },
        {
          "slug": "andressa-vesti",
          "nome": "Andressa Vesti",
          "arquetipo": "rebelde",
          "tem_conta": true,
          "email": "andressavazpinto@gmail.commx",
          "produtos": 8,
          "estimado": true,
          "produtos_7d": 0,
          "ativa": false,
          "acessos": 2,
          "buscas": 1,
          "descricoes": 0,
          "envios": 0,
          "primeiro": "2026-08-14T12:06:46.387Z",
          "ultimo": "2026-08-20T02:30:36.116Z",
          "dias": 50,
          "produtos_medidos": 0,
          "atribuido": 8
        },
        {
          "slug": "optimist-jeans",
          "nome": "Optimist Jeans",
          "arquetipo": "governante",
          "tem_conta": true,
          "email": "ecommerce@optimistjeans.com.br",
          "produtos": 3,
          "estimado": true,
          "produtos_7d": 0,
          "ativa": false,
          "acessos": 0,
          "buscas": 0,
          "descricoes": 0,
          "envios": 0,
          "primeiro": "",
          "ultimo": "",
          "dias": null,
          "produtos_medidos": 0,
          "atribuido": 3
        },
        {
          "slug": "monnika-marikinha",
          "nome": "Monnika Marikinha",
          "arquetipo": "amante",
          "tem_conta": true,
          "email": "monnikamarikinhaloja@gmail.com",
          "produtos": 2,
          "estimado": true,
          "produtos_7d": 0,
          "ativa": false,
          "acessos": 0,
          "buscas": 0,
          "descricoes": 0,
          "envios": 0,
          "primeiro": "",
          "ultimo": "",
          "dias": null,
          "produtos_medidos": 0,
          "atribuido": 2
        },
        {
          "slug": "optimist-feirinha",
          "nome": "Optimist Feirinha",
          "arquetipo": "",
          "tem_conta": true,
          "email": "ecommerce@optimistjeans.com.br",
          "produtos": 2,
          "estimado": true,
          "produtos_7d": 0,
          "ativa": false,
          "acessos": 0,
          "buscas": 0,
          "descricoes": 0,
          "envios": 0,
          "primeiro": "",
          "ultimo": "",
          "dias": null,
          "produtos_medidos": 0,
          "atribuido": 2
        },
        {
          "slug": "trimix",
          "nome": "Trimix",
          "arquetipo": "heroi",
          "tem_conta": true,
          "email": "salomon@trimix.com.br",
          "produtos": 1,
          "estimado": true,
          "produtos_7d": 0,
          "ativa": false,
          "acessos": 22,
          "buscas": 61,
          "descricoes": 58,
          "envios": 0,
          "primeiro": "2026-08-14T11:49:43.332Z",
          "ultimo": "2026-10-09T16:19:18.109Z",
          "dias": 0,
          "produtos_medidos": 0,
          "atribuido": 1
        },
        {
          "slug": "anne-blanc",
          "nome": "Anne Blanc",
          "arquetipo": "",
          "tem_conta": false,
          "email": "",
          "produtos": 0,
          "estimado": false,
          "produtos_7d": 0,
          "ativa": false,
          "acessos": 0,
          "buscas": 0,
          "descricoes": 0,
          "envios": 0,
          "primeiro": "",
          "ultimo": "",
          "dias": null,
          "produtos_medidos": 0,
          "atribuido": 0
        },
        {
          "slug": "demissy",
          "nome": "DeMissy",
          "arquetipo": "",
          "tem_conta": true,
          "email": "comercial.danque@gmail.com",
          "produtos": 0,
          "estimado": false,
          "produtos_7d": 0,
          "ativa": false,
          "acessos": 0,
          "buscas": 0,
          "descricoes": 0,
          "envios": 0,
          "primeiro": "",
          "ultimo": "",
          "dias": null,
          "produtos_medidos": 0,
          "atribuido": 0
        },
        {
          "slug": "gitaa",
          "nome": "Gitaa",
          "arquetipo": "",
          "tem_conta": false,
          "email": "",
          "produtos": 0,
          "estimado": false,
          "produtos_7d": 0,
          "ativa": false,
          "acessos": 0,
          "buscas": 0,
          "descricoes": 0,
          "envios": 0,
          "primeiro": "",
          "ultimo": "",
          "dias": null,
          "produtos_medidos": 0,
          "atribuido": 0
        },
        {
          "slug": "kauly-varejo",
          "nome": "Kauly varejo",
          "arquetipo": "",
          "tem_conta": false,
          "email": "",
          "produtos": 0,
          "estimado": false,
          "produtos_7d": 0,
          "ativa": false,
          "acessos": 0,
          "buscas": 0,
          "descricoes": 0,
          "envios": 0,
          "primeiro": "",
          "ultimo": "",
          "dias": null,
          "produtos_medidos": 0,
          "atribuido": 0
        },
        {
          "slug": "murano",
          "nome": "Murano",
          "arquetipo": "",
          "tem_conta": false,
          "email": "",
          "produtos": 0,
          "estimado": false,
          "produtos_7d": 0,
          "ativa": false,
          "acessos": 0,
          "buscas": 0,
          "descricoes": 0,
          "envios": 0,
          "primeiro": "",
          "ultimo": "",
          "dias": null,
          "produtos_medidos": 0,
          "atribuido": 0
        },
        {
          "slug": "murano-filial",
          "nome": "Murano filial",
          "arquetipo": "",
          "tem_conta": false,
          "email": "",
          "produtos": 0,
          "estimado": false,
          "produtos_7d": 0,
          "ativa": false,
          "acessos": 0,
          "buscas": 0,
          "descricoes": 0,
          "envios": 0,
          "primeiro": "",
          "ultimo": "",
          "dias": null,
          "produtos_medidos": 0,
          "atribuido": 0
        },
        {
          "slug": "stefani",
          "nome": "Stefani",
          "arquetipo": "",
          "tem_conta": false,
          "email": "",
          "produtos": 0,
          "estimado": false,
          "produtos_7d": 0,
          "ativa": false,
          "acessos": 0,
          "buscas": 0,
          "descricoes": 0,
          "envios": 0,
          "primeiro": "",
          "ultimo": "",
          "dias": null,
          "produtos_medidos": 0,
          "atribuido": 0
        },
        {
          "slug": "ttng",
          "nome": "TTNG",
          "arquetipo": "",
          "tem_conta": false,
          "email": "",
          "produtos": 0,
          "estimado": false,
          "produtos_7d": 0,
          "ativa": false,
          "acessos": 0,
          "buscas": 0,
          "descricoes": 0,
          "envios": 0,
          "primeiro": "",
          "ultimo": "",
          "dias": null,
          "produtos_medidos": 0,
          "atribuido": 0
        }
      ],
      "semanas": [
        {
          "inicio": "2026-07-20",
          "fim": "2026-07-26",
          "produtos": 0,
          "ativas": 0,
          "usaram": 0,
          "cadastros": 5,
          "novos": 2,
          "produtos_medidos": 0,
          "atribuido": 0
        },
        {
          "inicio": "2026-07-27",
          "fim": "2026-08-02",
          "produtos": 13,
          "ativas": 0,
          "usaram": 0,
          "cadastros": 5,
          "novos": 0,
          "produtos_medidos": 0,
          "atribuido": 13
        },
        {
          "inicio": "2026-08-03",
          "fim": "2026-08-09",
          "produtos": 21,
          "ativas": 0,
          "usaram": 0,
          "cadastros": 7,
          "novos": 2,
          "produtos_medidos": 0,
          "atribuido": 21
        },
        {
          "inicio": "2026-08-10",
          "fim": "2026-08-16",
          "produtos": 99,
          "ativas": 0,
          "usaram": 3,
          "cadastros": 9,
          "novos": 2,
          "produtos_medidos": 0,
          "atribuido": 99
        },
        {
          "inicio": "2026-08-17",
          "fim": "2026-08-23",
          "produtos": 60,
          "ativas": 2,
          "usaram": 4,
          "cadastros": 9,
          "novos": 0,
          "produtos_medidos": 12,
          "atribuido": 48
        },
        {
          "inicio": "2026-08-24",
          "fim": "2026-08-30",
          "produtos": 67,
          "ativas": 1,
          "usaram": 2,
          "cadastros": 9,
          "novos": 0,
          "produtos_medidos": 7,
          "atribuido": 60
        },
        {
          "inicio": "2026-08-31",
          "fim": "2026-09-06",
          "produtos": 37,
          "ativas": 1,
          "usaram": 3,
          "cadastros": 10,
          "novos": 1,
          "produtos_medidos": 8,
          "atribuido": 29
        },
        {
          "inicio": "2026-09-07",
          "fim": "2026-09-13",
          "produtos": 272,
          "ativas": 2,
          "usaram": 4,
          "cadastros": 10,
          "novos": 0,
          "produtos_medidos": 246,
          "atribuido": 26
        },
        {
          "inicio": "2026-09-14",
          "fim": "2026-09-20",
          "produtos": 30,
          "ativas": 2,
          "usaram": 3,
          "cadastros": 10,
          "novos": 0,
          "produtos_medidos": 21,
          "atribuido": 9
        },
        {
          "inicio": "2026-09-21",
          "fim": "2026-09-27",
          "produtos": 1126,
          "ativas": 1,
          "usaram": 3,
          "cadastros": 10,
          "novos": 0,
          "produtos_medidos": 9,
          "atribuido": 1117
        },
        {
          "inicio": "2026-09-28",
          "fim": "2026-10-04",
          "produtos": 30,
          "ativas": 2,
          "usaram": 3,
          "cadastros": 10,
          "novos": 0,
          "produtos_medidos": 28,
          "atribuido": 2
        },
        {
          "inicio": "2026-10-05",
          "fim": "2026-10-11",
          "produtos": 21,
          "ativas": 2,
          "usaram": 3,
          "cadastros": 10,
          "novos": 0,
          "produtos_medidos": 18,
          "atribuido": 3
        }
      ]
    }
  }
};
